
package com.sino.soa.mis.eip.fi.gl.sb_fi_gl_inquiryouorganizationsrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Sep 08 15:32:12 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIGLInquiryOuOrganizationSrv_SBFIGLInquiryOuOrganizationSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/common/gl/SB_FI_GL_InquiryOuOrganizationSrv", "SB_FI_GL_InquiryOuOrganizationSrv");

    private SBFIGLInquiryOuOrganizationSrv_SBFIGLInquiryOuOrganizationSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIGLInquiryOuOrganizationSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIGLInquiryOuOrganizationSrv_Service ss = new SBFIGLInquiryOuOrganizationSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIGLInquiryOuOrganizationSrv port = ss.getSBFIGLInquiryOuOrganizationSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.fi.gl.sb_fi_gl_inquiryouorganizationsrv.inquiryouorganizationsrv.InquiryOuOrganizationSrvRequest _process_payload = null;
        com.sino.soa.mis.eip.fi.gl.sb_fi_gl_inquiryouorganizationsrv.inquiryouorganizationsrv.InquiryOuOrganizationSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
