package com.sino.soa.mis.eip.fi.gl.sb_fi_gl_pageinquiryaccountbalancesrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Oct 15 16:24:56 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://mss.cmcc.com/SB_FI_GL_PageInquiryAccountBalanceSrv", name = "SB_FI_GL_PageInquiryAccountBalanceSrv")
@XmlSeeAlso({ObjectFactory.class, com.sino.soa.mis.eip.fi.gl.sb_fi_gl_pageinquiryaccountbalancesrv.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIGLPageInquiryAccountBalanceSrv {

    @WebResult(name = "SB_FI_GL_PageInquiryAccountBalanceSrvResponse", targetNamespace = "http://mss.cmcc.com/SB_FI_GL_PageInquiryAccountBalanceSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIGLPageInquiryAccountBalanceSrvResponse process(
        @WebParam(partName = "payload", name = "SB_FI_GL_PageInquiryAccountBalanceSrvRequest", targetNamespace = "http://mss.cmcc.com/SB_FI_GL_PageInquiryAccountBalanceSrv")
        SBFIGLPageInquiryAccountBalanceSrvRequest payload
    );
}
