
/*
 * 
 */

package com.sino.soa.mis.eip.hr.hr.sb_hr_hr_pageinquiryempassigninfosrv;

import com.sino.soa.common.SOAConstant;
import com.sino.soa.common.SOAVersion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 15:14:51 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_HR_HR_PageInquiryEmpAssignInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/hr/SB_HR_HR_PageInquiryEmpAssignInfoSrv/" + SOAVersion.EMP_ASSIGN_INFO_SRV_VERSION + "/SB_HR_HR_PageInquiryEmpAssignInfoSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/common/fi/SB_HR_HR_PageInquiryEmpAssignInfoSrv") 
public class SBHRHRPageInquiryEmpAssignInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/common/fi/SB_HR_HR_PageInquiryEmpAssignInfoSrv", "SB_HR_HR_PageInquiryEmpAssignInfoSrv");
    public final static QName SBHRHRPageInquiryEmpAssignInfoSrvPort = new QName("http://eip.zte.com/common/fi/SB_HR_HR_PageInquiryEmpAssignInfoSrv", "SB_HR_HR_PageInquiryEmpAssignInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/hr/SB_HR_HR_PageInquiryEmpAssignInfoSrv/" + SOAVersion.EMP_ASSIGN_INFO_SRV_VERSION + "/SB_HR_HR_PageInquiryEmpAssignInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/hr/SB_HR_HR_PageInquiryEmpAssignInfoSrv/" + SOAVersion.EMP_ASSIGN_INFO_SRV_VERSION + "/SB_HR_HR_PageInquiryEmpAssignInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBHRHRPageInquiryEmpAssignInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBHRHRPageInquiryEmpAssignInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBHRHRPageInquiryEmpAssignInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBHRHRPageInquiryEmpAssignInfoSrv
     */
    @WebEndpoint(name = "SB_HR_HR_PageInquiryEmpAssignInfoSrvPort")
    public SBHRHRPageInquiryEmpAssignInfoSrv getSBHRHRPageInquiryEmpAssignInfoSrvPort() {
        return super.getPort(SBHRHRPageInquiryEmpAssignInfoSrvPort, SBHRHRPageInquiryEmpAssignInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBHRHRPageInquiryEmpAssignInfoSrv
     */
    @WebEndpoint(name = "SB_HR_HR_PageInquiryEmpAssignInfoSrvPort")
    public SBHRHRPageInquiryEmpAssignInfoSrv getSBHRHRPageInquiryEmpAssignInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBHRHRPageInquiryEmpAssignInfoSrvPort, SBHRHRPageInquiryEmpAssignInfoSrv.class, features);
    }

}
