package com.sino.soa.td.srv.assetsinfoupdate.srv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.sino.soa.common.SrvReturnMessage;
import com.sino.soa.util.XMLGregorianCalendarUtil;
import com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATDTransAssetHeaderInfoSrv;
import com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrv;
import com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrvProcessRequest;
import com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrvProcessResponse;

import javax.xml.namespace.QName;
import java.net.URL;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import com.sino.base.util.StrUtil;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Aug 19 01:16:04 CST 2009
 * Generated source version: 2.1.4
 * 查询资产信息头信息ODI_TD
 */

public final class TDTransAssetHeaderInfoSrv {
    private SrvReturnMessage returnMessage = new SrvReturnMessage();

    private String envCode = "";
    private String bookTypeCode = "";
    private String startLastUpdateDate = "";
    private String endLastUpdateDate = "";
    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetHeaderInfoSrv", "SB_FI_FA_TDTransAssetHeaderInfoSrv");

    public TDTransAssetHeaderInfoSrv() {
    }


    public void excute() throws Exception {
        URL wsdlURL = SBFIFATDTransAssetHeaderInfoSrv.WSDL_LOCATION;


        SBFIFATDTransAssetHeaderInfoSrv ss = new SBFIFATDTransAssetHeaderInfoSrv(wsdlURL, SERVICE_NAME);
        SBFIFATransAssetHeaderInfoSrv port = ss.getSBFIFATransAssetHeaderInfoSrvPort();

        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();

        httpClientPolicy.setConnectionTimeout(5400000);//连接时间
        httpClientPolicy.setReceiveTimeout(5400000);//接收时间
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);

        {
            System.out.println("SB_FI_FA_TDTransAssetHeaderInfoSrv Invoking process...");
            SBFIFATransAssetHeaderInfoSrvProcessRequest _process_payload = null;
            _process_payload = new SBFIFATransAssetHeaderInfoSrvProcessRequest();
            _process_payload.setBOOKTYPECODE(bookTypeCode);
            _process_payload.setENVCODE(envCode);
            _process_payload.setSTARTLASTUPDATEDATE(XMLGregorianCalendarUtil.getXMLGregorianCalendar(startLastUpdateDate));
            _process_payload.setENDLASTUPDATEDATE(XMLGregorianCalendarUtil.getXMLGregorianCalendar(endLastUpdateDate));
            SBFIFATransAssetHeaderInfoSrvProcessResponse _process__return = port.process(_process_payload);
            returnMessage.setErrorFlag(StrUtil.nullToString(_process__return.getERRORFLAG()));
            returnMessage.setErrorMessage(_process__return.getERRORMESSAGE());
            System.out.println("是否成功：---------" + returnMessage.getErrorFlag());
            System.out.println("错误信息：---------" + returnMessage.getErrorMessage());

        }
    }

    public SrvReturnMessage getReturnMessage() {
        return returnMessage;
    }

    public String getEnvCode() {
        return envCode;
    }

    public void setEnvCode(String envCode) {
        this.envCode = envCode;
    }

    public String getBookTypeCode() {
        return bookTypeCode;
    }

    public void setBookTypeCode(String bookTypeCode) {
        this.bookTypeCode = bookTypeCode;
    }

    public String getStartLastUpdateDate() {
        return startLastUpdateDate;
    }

    public void setStartLastUpdateDate(String startLastUpdateDate) {
        this.startLastUpdateDate = startLastUpdateDate;
    }

    public String getEndLastUpdateDate() {
        return endLastUpdateDate;
    }

    public void setEndLastUpdateDate(String endLastUpdateDate) {
        this.endLastUpdateDate = endLastUpdateDate;
    }

    public static void main(String[] args) throws Exception {
        TDTransAssetHeaderInfoSrv srv = new TDTransAssetHeaderInfoSrv();
        srv.setEnvCode("SN_EAMS_TransAssetHeaderInfoSrv");
        srv.setBookTypeCode("SNMC_FA_8010");
        srv.setStartLastUpdateDate("2008-03-01");
        srv.setEndLastUpdateDate("2008-08-01");
        srv.excute();
    }
}