
/*
 * 
 */

package com.sino.soa.mis.eip.sc.pa.sb_sc_pa_pageinquirytaskinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Oct 14 14:39:19 CST 2011
 * Generated source version: 2.1.4
 * 查询项目任务信息服务(分页)
 */

@WebServiceClient(name = "SB_SC_PA_PageInquiryTaskInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PA_PageInquiryTaskInfoSrv/4.0/SB_SC_PA_PageInquiryTaskInfoSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryTaskInfoSrv") 
public class SBSCPAPageInquiryTaskInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/SC/SB_SC_PA_PageInquiryTaskInfoSrv", "SB_SC_PA_PageInquiryTaskInfoSrv");
    public final static QName SBSCPAPageInquiryTaskInfoSrvPort = new QName("http://eip.zte.com/SC/SB_SC_PA_PageInquiryTaskInfoSrv", "SB_SC_PA_PageInquiryTaskInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PA_PageInquiryTaskInfoSrv/4.0/SB_SC_PA_PageInquiryTaskInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PA_PageInquiryTaskInfoSrv/4.0/SB_SC_PA_PageInquiryTaskInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBSCPAPageInquiryTaskInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBSCPAPageInquiryTaskInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBSCPAPageInquiryTaskInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBSCPAPageInquiryTaskInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PA_PageInquiryTaskInfoSrvPort")
    public SBSCPAPageInquiryTaskInfoSrv getSBSCPAPageInquiryTaskInfoSrvPort() {
        return super.getPort(SBSCPAPageInquiryTaskInfoSrvPort, SBSCPAPageInquiryTaskInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBSCPAPageInquiryTaskInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PA_PageInquiryTaskInfoSrvPort")
    public SBSCPAPageInquiryTaskInfoSrv getSBSCPAPageInquiryTaskInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBSCPAPageInquiryTaskInfoSrvPort, SBSCPAPageInquiryTaskInfoSrv.class, features);
    }

}
