package com.sino.ams.spare.assistant;

import com.sino.ams.constant.CustMessageKey;

public interface SpareMessageKeys extends CustMessageKey {
	String SAVE_SUCCESS = "SAVE_SUCCESS";
	String SAVE_FAILURE = "SAVE_FAILURE";

	String TRANS_SUBMIT_SUCCESS = "TRANS_SUBMIT_SUCCESS";
	String TRANS_SUBMIT_FAILURE = "TRANS_SUBMIT_FAILURE";
	String TRANS_APPROVE_SUCCESS = "TRANS_APPROVE_SUCCESS";
	String TRANS_APPROVE_FAILURE = "TRANS_APPROVE_FAILURE";
	String REPAIR_SUBMIT_SUCCESS = "REPAIR_SUBMIT_SUCCESS";
	String REPAIR_SUBMIT_FAILURE = "REPAIR_SUBMIT_FAILURE";


	String WAREIN_SUCCESS = "WAREIN_SUCCESS";
	String WAREIN_SUBMIT_SUCCESS = "WAREIN_SUBMIT_SUCCESS";
	String WAREIN_FAILURE = "WAREIN_FAILURE";


	String WAREOUT_SUBMIT_SUCCESS = "WAREOUT_SUBMIT_SUCCESS";
	String WAREOUT_SUBMIT_FAILURE = "WAREOUT_SUBMIT_FAILURE";
	String WAREOUT_APPROVE_SUCCESS = "WAREOUT_APPROVE_SUCCESS";
	String WAREOUT_APPROVE_FAILURE = "WAREOUT_APPROVE_FAILURE";

	String APPLY_APPROVE_SUCCESS = "APPLY_APPROVE_SUCCESS";
	String APPLY_APPROVE_FAILURE = "APPLY_APPROVE_FAILURE";

	String APPLY_REJECT_SUCCESS = "APPLY_REJECT_SUCCESS";
	String APPLY_REJECT_FAILURE = "APPLY_REJECT_FAILURE";

	String TRANS_REJECT_SUCCESS = "APPLY_REJECT_SUCCESS";
	String TRANS_REJECT_FAILURE = "APPLY_REJECT_FAILURE";
}
