package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_inquiryassetbooksrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Sep 05 19:24:26 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_InquiryAssetBookSrv", name = "SB_FI_FA_InquiryAssetBookSrv")
@XmlSeeAlso({com.sino.soa.mis.eip.fi.fa.sb_fi_fa_inquiryassetbooksrv.msgheader.ObjectFactory.class,ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFAInquiryAssetBookSrv {

    @WebResult(name = "InquiryAssetBookSrvResponse", targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_InquiryAssetBookSrv", partName = "payload")
    @WebMethod(action = "process")
    public InquiryAssetBookSrvResponse process(
        @WebParam(partName = "payload", name = "InquiryAssetBookSrvRequest", targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_InquiryAssetBookSrv")
        InquiryAssetBookSrvRequest payload
    );
}
