
/*
 * 
 */

package com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sun Oct 16 23:29:17 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TDCreateAssetTransferInCompanySrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDCreateAssetTransferInCompanySrv/1.0/SB_FI_FA_TDCreateAssetTransferInCompanySrv?wsdl",
                  targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferInCompanySrv") 
public class SBFIFATDCreateAssetTransferInCompanySrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferInCompanySrv", "SB_FI_FA_TDCreateAssetTransferInCompanySrv");
    public final static QName SBFIFACreateAssetTransferInCompanySrvPort = new QName("http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferInCompanySrv", "SB_FI_FA_CreateAssetTransferInCompanySrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDCreateAssetTransferInCompanySrv/1.0/SB_FI_FA_TDCreateAssetTransferInCompanySrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDCreateAssetTransferInCompanySrv/1.0/SB_FI_FA_TDCreateAssetTransferInCompanySrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATDCreateAssetTransferInCompanySrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATDCreateAssetTransferInCompanySrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATDCreateAssetTransferInCompanySrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFACreateAssetTransferInCompanySrv
     */
    @WebEndpoint(name = "SB_FI_FA_CreateAssetTransferInCompanySrvPort")
    public SBFIFACreateAssetTransferInCompanySrv getSBFIFACreateAssetTransferInCompanySrvPort() {
        return super.getPort(SBFIFACreateAssetTransferInCompanySrvPort, SBFIFACreateAssetTransferInCompanySrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFACreateAssetTransferInCompanySrv
     */
    @WebEndpoint(name = "SB_FI_FA_CreateAssetTransferInCompanySrvPort")
    public SBFIFACreateAssetTransferInCompanySrv getSBFIFACreateAssetTransferInCompanySrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFACreateAssetTransferInCompanySrvPort, SBFIFACreateAssetTransferInCompanySrv.class, features);
    }

}
