
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetdistributionsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:18:58 CST 2011
 * Generated source version: 2.1.4
 * 查询资产分配行信息_非TD(ODI)
 */


@WebServiceClient(name = "SB_FI_FA_TransAssetDistributionSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetDistributionSrv/1.0/SB_FI_FA_TransAssetDistributionSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDistributionSrv") 
public class SBFIFATransAssetDistributionSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetDistributionSrv", "SB_FI_FA_TransAssetDistributionSrv");
    public final static QName SBFIFATransAssetDistributionSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetDistributionSrv", "SB_FI_FA_TransAssetDistributionSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetDistributionSrv/1.0/SB_FI_FA_TransAssetDistributionSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetDistributionSrv/1.0/SB_FI_FA_TransAssetDistributionSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATransAssetDistributionSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATransAssetDistributionSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATransAssetDistributionSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFATransAssetDistributionSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransAssetDistributionSrvPort")
    public SBFIFATransAssetDistributionSrv getSBFIFATransAssetDistributionSrvPort() {
        return super.getPort(SBFIFATransAssetDistributionSrvPort, SBFIFATransAssetDistributionSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFATransAssetDistributionSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransAssetDistributionSrvPort")
    public SBFIFATransAssetDistributionSrv getSBFIFATransAssetDistributionSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFATransAssetDistributionSrvPort, SBFIFATransAssetDistributionSrv.class, features);
    }

}
