package com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetdeprecationsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Oct 12 16:37:32 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDeprecationSrv", name = "SB_FI_FA_TransAssetDeprecationSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFATransAssetDeprecationSrv {

    @WebResult(name = "SB_FI_FA_TransAssetDeprecationSrvProcessResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDeprecationSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIFATransAssetDeprecationSrvProcessResponse process(
        @WebParam(partName = "payload", name = "SB_FI_FA_TransAssetDeprecationSrvProcessRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDeprecationSrv")
        SBFIFATransAssetDeprecationSrvProcessRequest payload
    );
}
