
/*
 * 
 */

package com.sino.soa.mis.eip.odi.sb_fi_fa_transfaassetinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Feb 17 16:40:13 CST 2012
 * Generated source version: 2.1.4
 * MIS资产财务信息(ODI)_new 
 */


@WebServiceClient(name = "SB_FI_FA_TransFaAssetInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransFaAssetInfoSrv/1.0/SB_FI_FA_TransFaAssetInfoSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransFaAssetInfoSrv") 
public class SBFIFATransFaAssetInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_TransFaAssetInfoSrv", "SB_FI_FA_TransFaAssetInfoSrv");
    public final static QName SBFIFATransFaAssetInfoSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_TransFaAssetInfoSrv", "SB_FI_FA_TransFaAssetInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransFaAssetInfoSrv/1.0/SB_FI_FA_TransFaAssetInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransFaAssetInfoSrv/1.0/SB_FI_FA_TransFaAssetInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATransFaAssetInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATransFaAssetInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATransFaAssetInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFATransFaAssetInfoSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransFaAssetInfoSrvPort")
    public SBFIFATransFaAssetInfoSrv getSBFIFATransFaAssetInfoSrvPort() {
        return super.getPort(SBFIFATransFaAssetInfoSrvPort, SBFIFATransFaAssetInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFATransFaAssetInfoSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransFaAssetInfoSrvPort")
    public SBFIFATransFaAssetInfoSrv getSBFIFATransFaAssetInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFATransFaAssetInfoSrvPort, SBFIFATransFaAssetInfoSrv.class, features);
    }

}
