
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_pageinquiryassetheaderinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;
 
/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Oct 14 14:33:03 CST 2011
 * Generated source version: 2.1.4
 * 查询资产头基本信息（分页）
 */


@WebServiceClient(name = "SB_FI_FA_PageInquiryAssetHeaderInfoSrv", 
                  wsdlLocation =  "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_PageInquiryAssetHeaderInfoSrv/1.0/SB_FI_FA_PageInquiryAssetHeaderInfoSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetHeaderInfoSrv") 
public class SBFIFAPageInquiryAssetHeaderInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetHeaderInfoSrv", "SB_FI_FA_PageInquiryAssetHeaderInfoSrv");
    public final static QName SBFIFAPageInquiryAssetHeaderInfoSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetHeaderInfoSrv", "SB_FI_FA_PageInquiryAssetHeaderInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL( "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_PageInquiryAssetHeaderInfoSrv/1.0/SB_FI_FA_PageInquiryAssetHeaderInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from  http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_PageInquiryAssetHeaderInfoSrv/1.0/SB_FI_FA_PageInquiryAssetHeaderInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFAPageInquiryAssetHeaderInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFAPageInquiryAssetHeaderInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFAPageInquiryAssetHeaderInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAPageInquiryAssetHeaderInfoSrv
     */
    @WebEndpoint(name = "SB_FI_FA_PageInquiryAssetHeaderInfoSrvPort")
    public SBFIFAPageInquiryAssetHeaderInfoSrv getSBFIFAPageInquiryAssetHeaderInfoSrvPort() {
        return super.getPort(SBFIFAPageInquiryAssetHeaderInfoSrvPort, SBFIFAPageInquiryAssetHeaderInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAPageInquiryAssetHeaderInfoSrv
     */
    @WebEndpoint(name = "SB_FI_FA_PageInquiryAssetHeaderInfoSrvPort")
    public SBFIFAPageInquiryAssetHeaderInfoSrv getSBFIFAPageInquiryAssetHeaderInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAPageInquiryAssetHeaderInfoSrvPort, SBFIFAPageInquiryAssetHeaderInfoSrv.class, features);
    }

}
