package com.sino.ams.apd.model;

import java.util.ArrayList;
import java.util.List;

import com.sino.ams.apd.dto.AmsAssetsCheckByYrHeaderDTO;
import com.sino.ams.apd.dto.AmsAssetsCheckOrderDTO;
import com.sino.ams.system.user.dto.SfUserDTO;
import com.sino.base.db.sql.model.SQLModel;
import com.sino.framework.sql.BaseSQLProducer;

public class AmsAssetsCheckOrderModel extends BaseSQLProducer {
	private SfUserDTO user = null;

	public AmsAssetsCheckOrderModel(SfUserDTO userAccount,
			AmsAssetsCheckOrderDTO dtoParameter) {
		super(userAccount, dtoParameter);
		this.user = userAccount;
	}

	public SQLModel getLineModel() {
		SQLModel sqlModel = new SQLModel();
		List sqlArgs = new ArrayList();
		AmsAssetsCheckOrderDTO dto = (AmsAssetsCheckOrderDTO) this.dtoParameter;
		String creationType=dto.getCreationType();//实地非实地盘点资产
		
		String sqlStr="";
		if(creationType.equals("N")){//非实地盘点资产
			String sendType=dto.getSendType();
			if(sendType.equals("SOFTWARE")){//按资产种类(软件)
				sqlStr= " SELECT SYSTEMID, BARCODE, VENDOR_BARCODE, ITEM_QTY, DISABLE_DATE, REMARK, START_DATE, ITEM_CODE, " +
						" PROJECTID, ITEM_STATUS, ATTRIBUTE1, ATTRIBUTE2, SENDTOMIS_FLAG, MIS_ITEMNAME, MIS_ITEMSPEC, " +
						" CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_BY, ASSET_ID, ADDRESS_ID, FINANCE_PROP," +
						" ATTRIBUTE3, PARENT_BARCODE, LAST_LOC_CHG_DATE, ORGANIZATION_ID, FA_BARCODE, IS_PARENT," +
						" RESPONSIBILITY_USER, RESPONSIBILITY_DEPT, MAINTAIN_USER, MAINTAIN_DEPT, MANUFACTURER_ID, IS_SHARE, " +
						" CONTENT_CODE, CONTENT_NAME, POWER, LNE_ID, CEX_ID, OPE_ID, NLE_ID, IS_TMP, PRICE, OLD_CONTENT_CODE, " +
						" OLD_CONTENT_NAME, REP_MANUFACTURER_ID, SPECIALITY_DEPT, DZYH_ADDRESS, OTHER_INFO, SHARE_STATUS, IS_TD, " +
						" ACTUAL_QTY, IS_RENTAL, REMARK1, REMARK2, UNIT_OF_MEASURE, DISCARD_TYPE, DEAL_TYPE, REFER_NATIONAL_FUND," +
						" SN_ID, CONSTRUCT_STATUS, TF_NET_ASSET_VALUE, TF_DEPRN_COST, TF_DEPRECIATION, OLD_BARCODE, " +
						" SPECIALITY_USER2, SPECIALITY_USER, ARRIVAL_DATE " +
						" FROM   ETS_ITEM_INFO" +
						" WHERE CONTENT_CODE like '%9999'";
				
			}else if(sendType.equals("PIP")){//按资产种类(光缆、杆路及管道)
						sqlStr= " SELECT SYSTEMID, BARCODE, VENDOR_BARCODE, ITEM_QTY, DISABLE_DATE, REMARK, START_DATE, ITEM_CODE, " +
						" PROJECTID, ITEM_STATUS, ATTRIBUTE1, ATTRIBUTE2, SENDTOMIS_FLAG, MIS_ITEMNAME, MIS_ITEMSPEC, " +
						" CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_BY, ASSET_ID, ADDRESS_ID, FINANCE_PROP," +
						" ATTRIBUTE3, PARENT_BARCODE, LAST_LOC_CHG_DATE, ORGANIZATION_ID, FA_BARCODE, IS_PARENT," +
						" RESPONSIBILITY_USER, RESPONSIBILITY_DEPT, MAINTAIN_USER, MAINTAIN_DEPT, MANUFACTURER_ID, IS_SHARE, " +
						" CONTENT_CODE, CONTENT_NAME, POWER, LNE_ID, CEX_ID, OPE_ID, NLE_ID, IS_TMP, PRICE, OLD_CONTENT_CODE, " +
						" OLD_CONTENT_NAME, REP_MANUFACTURER_ID, SPECIALITY_DEPT, DZYH_ADDRESS, OTHER_INFO, SHARE_STATUS, IS_TD, " +
						" ACTUAL_QTY, IS_RENTAL, REMARK1, REMARK2, UNIT_OF_MEASURE, DISCARD_TYPE, DEAL_TYPE, REFER_NATIONAL_FUND," +
						" SN_ID, CONSTRUCT_STATUS, TF_NET_ASSET_VALUE, TF_DEPRN_COST, TF_DEPRECIATION, OLD_BARCODE, " +
						" SPECIALITY_USER2, SPECIALITY_USER, ARRIVAL_DATE " +
						" FROM   ETS_ITEM_INFO" +
						" WHERE CONTENT_CODE like '%.04-05%'" +//光缆
						" UNION ALL  "+
						" SELECT SYSTEMID, BARCODE, VENDOR_BARCODE, ITEM_QTY, DISABLE_DATE, REMARK, START_DATE, ITEM_CODE, " +
						" PROJECTID, ITEM_STATUS, ATTRIBUTE1, ATTRIBUTE2, SENDTOMIS_FLAG, MIS_ITEMNAME, MIS_ITEMSPEC, " +
						" CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_BY, ASSET_ID, ADDRESS_ID, FINANCE_PROP," +
						" ATTRIBUTE3, PARENT_BARCODE, LAST_LOC_CHG_DATE, ORGANIZATION_ID, FA_BARCODE, IS_PARENT," +
						" RESPONSIBILITY_USER, RESPONSIBILITY_DEPT, MAINTAIN_USER, MAINTAIN_DEPT, MANUFACTURER_ID, IS_SHARE, " +
						" CONTENT_CODE, CONTENT_NAME, POWER, LNE_ID, CEX_ID, OPE_ID, NLE_ID, IS_TMP, PRICE, OLD_CONTENT_CODE, " +
						" OLD_CONTENT_NAME, REP_MANUFACTURER_ID, SPECIALITY_DEPT, DZYH_ADDRESS, OTHER_INFO, SHARE_STATUS, IS_TD, " +
						" ACTUAL_QTY, IS_RENTAL, REMARK1, REMARK2, UNIT_OF_MEASURE, DISCARD_TYPE, DEAL_TYPE, REFER_NATIONAL_FUND," +
						" SN_ID, CONSTRUCT_STATUS, TF_NET_ASSET_VALUE, TF_DEPRN_COST, TF_DEPRECIATION, OLD_BARCODE, " +
						" SPECIALITY_USER2, SPECIALITY_USER, ARRIVAL_DATE " +
						" FROM   ETS_ITEM_INFO" +
						" WHERE CONTENT_CODE like '%.04-07%'" +//杆路
						" UNION ALL "+
						" SELECT SYSTEMID, BARCODE, VENDOR_BARCODE, ITEM_QTY, DISABLE_DATE, REMARK, START_DATE, ITEM_CODE, " +
						" PROJECTID, ITEM_STATUS, ATTRIBUTE1, ATTRIBUTE2, SENDTOMIS_FLAG, MIS_ITEMNAME, MIS_ITEMSPEC, " +
						" CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_BY, ASSET_ID, ADDRESS_ID, FINANCE_PROP," +
						" ATTRIBUTE3, PARENT_BARCODE, LAST_LOC_CHG_DATE, ORGANIZATION_ID, FA_BARCODE, IS_PARENT," +
						" RESPONSIBILITY_USER, RESPONSIBILITY_DEPT, MAINTAIN_USER, MAINTAIN_DEPT, MANUFACTURER_ID, IS_SHARE, " +
						" CONTENT_CODE, CONTENT_NAME, POWER, LNE_ID, CEX_ID, OPE_ID, NLE_ID, IS_TMP, PRICE, OLD_CONTENT_CODE, " +
						" OLD_CONTENT_NAME, REP_MANUFACTURER_ID, SPECIALITY_DEPT, DZYH_ADDRESS, OTHER_INFO, SHARE_STATUS, IS_TD, " +
						" ACTUAL_QTY, IS_RENTAL, REMARK1, REMARK2, UNIT_OF_MEASURE, DISCARD_TYPE, DEAL_TYPE, REFER_NATIONAL_FUND," +
						" SN_ID, CONSTRUCT_STATUS, TF_NET_ASSET_VALUE, TF_DEPRN_COST, TF_DEPRECIATION, OLD_BARCODE, " +
						" SPECIALITY_USER2, SPECIALITY_USER, ARRIVAL_DATE " +
						" FROM   ETS_ITEM_INFO" +
						" WHERE CONTENT_CODE like '%.04-06%'" ;//管道
				
				
			}else if(sendType.equals("CLIENT")){//按资产种类(客户端资产)
						sqlStr=" SELECT SYSTEMID, BARCODE, VENDOR_BARCODE, ITEM_QTY, DISABLE_DATE, REMARK, START_DATE, ITEM_CODE, " +
						" PROJECTID, ITEM_STATUS, ATTRIBUTE1, ATTRIBUTE2, SENDTOMIS_FLAG, MIS_ITEMNAME, MIS_ITEMSPEC, " +
						" CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_BY, ASSET_ID, ADDRESS_ID, FINANCE_PROP," +
						" ATTRIBUTE3, PARENT_BARCODE, LAST_LOC_CHG_DATE, ORGANIZATION_ID, FA_BARCODE, IS_PARENT," +
						" RESPONSIBILITY_USER, RESPONSIBILITY_DEPT, MAINTAIN_USER, MAINTAIN_DEPT, MANUFACTURER_ID, IS_SHARE, " +
						" CONTENT_CODE, CONTENT_NAME, POWER, LNE_ID, CEX_ID, OPE_ID, NLE_ID, IS_TMP, PRICE, OLD_CONTENT_CODE, " +
						" OLD_CONTENT_NAME, REP_MANUFACTURER_ID, SPECIALITY_DEPT, DZYH_ADDRESS, OTHER_INFO, SHARE_STATUS, IS_TD, " +
						" ACTUAL_QTY, IS_RENTAL, REMARK1, REMARK2, UNIT_OF_MEASURE, DISCARD_TYPE, DEAL_TYPE, REFER_NATIONAL_FUND," +
						" SN_ID, CONSTRUCT_STATUS, TF_NET_ASSET_VALUE, TF_DEPRN_COST, TF_DEPRECIATION, OLD_BARCODE, " +
						" SPECIALITY_USER2, SPECIALITY_USER, ARRIVAL_DATE " +
						" FROM   ETS_ITEM_INFO EII" +
						"        AMS_OBJECT_ADDRESS AOA," +
						"        ETS_OBJECT EO" +
						" WHERE  EII.ADDRESS_ID=AOA.ADDRESS_ID" +
						" AND    AOA.OBJECT_NO=EO.WORKORDER_OBJECT_NO" +
						" AND    EO.OBJECT_CATEGORY_NAME='客户地点' " ;//管道
			}
			
		}else if(creationType.equals("Y")){//实地盘点资产
			
			
		}
		sqlModel.setSqlStr(sqlStr);
		sqlModel.setArgs(sqlArgs);
		return sqlModel;
	}
	
	@SuppressWarnings("unchecked")
	public SQLModel getCheckOrderModel(SfUserDTO user) {
		SQLModel sqlModel = new SQLModel();
		List sqlArgs = new ArrayList();
		String sqlStr = "";
		
		sqlStr="SELECT TRANS_ID, TRANS_NO, CRATE_DATE, TRANS_USER, TRANS_NAME, CREATION_TYPE, CREATE_VALUE, SEND_TYPE, SEND_VALUE" +
	           " FROM dbo.AMS_ASSETS_CHECK_ORDER WHERE TRANS_USER=?";
		sqlArgs.add(user.getUserId());
		sqlModel.setSqlStr(sqlStr);
		sqlModel.setArgs(sqlArgs);
		return sqlModel;
	}

}
