
package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_updateassetretirmentsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Sep 26 14:43:30 CST 2011
 * Generated source version: 2.1.4
 * Name: wangzhipeng
 * DSC: 资产基本信息修改接口(2011-09-26)_写入
 */


@WebServiceClient(name = "SB_FI_FA_UpdateAssetRetirmentSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_UpdateAssetRetirmentSrv/2.0/SB_FI_FA_UpdateAssetRetirmentSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/SB_FI_FA_UpdateAssetRetirmentSrv") 
public class SBFIFAUpdateAssetRetirmentSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/SB_FI_FA_UpdateAssetRetirmentSrv", "SB_FI_FA_UpdateAssetRetirmentSrv");
    public final static QName SBFIFAUpdateAssetRetirmentSrvPort = new QName("http://eip.zte.com/SB_FI_FA_UpdateAssetRetirmentSrv", "SB_FI_FA_UpdateAssetRetirmentSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_UpdateAssetRetirmentSrv/2.0/SB_FI_FA_UpdateAssetRetirmentSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_UpdateAssetRetirmentSrv/2.0/SB_FI_FA_UpdateAssetRetirmentSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFAUpdateAssetRetirmentSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFAUpdateAssetRetirmentSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFAUpdateAssetRetirmentSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAUpdateAssetRetirmentSrv
     */
    @WebEndpoint(name = "SB_FI_FA_UpdateAssetRetirmentSrvPort")
    public SBFIFAUpdateAssetRetirmentSrv getSBFIFAUpdateAssetRetirmentSrvPort() {
        return super.getPort(SBFIFAUpdateAssetRetirmentSrvPort, SBFIFAUpdateAssetRetirmentSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAUpdateAssetRetirmentSrv
     */
    @WebEndpoint(name = "SB_FI_FA_UpdateAssetRetirmentSrvPort")
    public SBFIFAUpdateAssetRetirmentSrv getSBFIFAUpdateAssetRetirmentSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAUpdateAssetRetirmentSrvPort, SBFIFAUpdateAssetRetirmentSrv.class, features);
    }

}
