package com.sino.soa.td.eip.sc.pa.sb_sc_pa_transtaskinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:53:48 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv", name = "SB_SC_PA_TransTaskInfoSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBSCPATransTaskInfoSrv {

    @WebResult(name = "SB_SC_PA_TransTaskInfoSrvProcessResponse", targetNamespace = "http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBSCPATransTaskInfoSrvProcessResponse process(
        @WebParam(partName = "payload", name = "SB_SC_PA_TransTaskInfoSrvProcessRequest", targetNamespace = "http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv")
        SBSCPATransTaskInfoSrvProcessRequest payload
    );
}
