
/*
 * 
 */

package com.sino.soa.td.eip.sc.pa.sb_sc_pa_transtaskinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:53:48 CST 2011
 * Generated source version: 2.1.4
 * 查询项目任务信息_TD(ODI)
 */ 


@WebServiceClient(name = "SB_SC_PA_TDTransTaskInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_SC_PA_TDTransTaskInfoSrv/1.0/SB_SC_PA_TDTransTaskInfoSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv") 
public class SBSCPATDTransTaskInfoSrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv", "SB_SC_PA_TDTransTaskInfoSrv");
    public final static QName SBSCPATransTaskInfoSrvPort = new QName("http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv", "SB_SC_PA_TransTaskInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_SC_PA_TDTransTaskInfoSrv/1.0/SB_SC_PA_TDTransTaskInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_SC_PA_TDTransTaskInfoSrv/1.0/SB_SC_PA_TDTransTaskInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBSCPATDTransTaskInfoSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBSCPATDTransTaskInfoSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBSCPATDTransTaskInfoSrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBSCPATransTaskInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PA_TransTaskInfoSrvPort")
    public SBSCPATransTaskInfoSrv getSBSCPATransTaskInfoSrvPort() {
        return super.getPort(SBSCPATransTaskInfoSrvPort, SBSCPATransTaskInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBSCPATransTaskInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PA_TransTaskInfoSrvPort")
    public SBSCPATransTaskInfoSrv getSBSCPATransTaskInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBSCPATransTaskInfoSrvPort, SBSCPATransTaskInfoSrv.class, features);
    }

}
