
package com.sino.soa.td.eip.fi.gl.sb_fi_gl_transaccountbalancesrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 13 11:25:44 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIGLTransAccountBalanceSrv_SBFIGLTransAccountBalanceSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_GL_TransAccountBalanceSrv", "SB_FI_GL_TDTransAccountBalanceSrv");

    private SBFIGLTransAccountBalanceSrv_SBFIGLTransAccountBalanceSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIGLTDTransAccountBalanceSrv.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIGLTDTransAccountBalanceSrv ss = new SBFIGLTDTransAccountBalanceSrv(wsdlURL, SERVICE_NAME);
        SBFIGLTransAccountBalanceSrv port = ss.getSBFIGLTransAccountBalanceSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.td.eip.fi.gl.sb_fi_gl_transaccountbalancesrv.SBFIGLTransAccountBalanceSrvProcessRequest _process_payload = null;
        com.sino.soa.td.eip.fi.gl.sb_fi_gl_transaccountbalancesrv.SBFIGLTransAccountBalanceSrvProcessResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
