
/*
 * 
 */

package com.sino.soa.td.eip.fi.gl.sb_fi_gl_transaccountbalancesrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 13 11:25:44 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_GL_TDTransAccountBalanceSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_GL_TDTransAccountBalanceSrv/1.0/SB_FI_GL_TDTransAccountBalanceSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_GL_TransAccountBalanceSrv") 
public class SBFIGLTDTransAccountBalanceSrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_GL_TransAccountBalanceSrv", "SB_FI_GL_TDTransAccountBalanceSrv");
    public final static QName SBFIGLTransAccountBalanceSrvPort = new QName("http://eip.zte.com/fi/SB_FI_GL_TransAccountBalanceSrv", "SB_FI_GL_TransAccountBalanceSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_GL_TDTransAccountBalanceSrv/1.0/SB_FI_GL_TDTransAccountBalanceSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_GL_TDTransAccountBalanceSrv/1.0/SB_FI_GL_TDTransAccountBalanceSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIGLTDTransAccountBalanceSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIGLTDTransAccountBalanceSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIGLTDTransAccountBalanceSrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIGLTransAccountBalanceSrv
     */
    @WebEndpoint(name = "SB_FI_GL_TransAccountBalanceSrvPort")
    public SBFIGLTransAccountBalanceSrv getSBFIGLTransAccountBalanceSrvPort() {
        return super.getPort(SBFIGLTransAccountBalanceSrvPort, SBFIGLTransAccountBalanceSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIGLTransAccountBalanceSrv
     */
    @WebEndpoint(name = "SB_FI_GL_TransAccountBalanceSrvPort")
    public SBFIGLTransAccountBalanceSrv getSBFIGLTransAccountBalanceSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIGLTransAccountBalanceSrvPort, SBFIGLTransAccountBalanceSrv.class, features);
    }

}
