
package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transfaassetinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Oct 20 09:47:45 CST 2011
 * Generated source version: 2.2.6
 * 
 */

public final class SBFIFATransFaAssetInfoSrv_SBFIFATransFaAssetInfoSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransFaAssetInfoSrv", "SB_FI_FA_TransFaAssetInfoSrv");

    private SBFIFATransFaAssetInfoSrv_SBFIFATransFaAssetInfoSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIFATransFaAssetInfoSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIFATransFaAssetInfoSrv_Service ss = new SBFIFATransFaAssetInfoSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFATransFaAssetInfoSrv port = ss.getSBFIFATransFaAssetInfoSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transfaassetinfosrv.SBFIFATransFaAssetInfoSrvProcessRequest _process_payload = new SBFIFATransFaAssetInfoSrvProcessRequest();
        
        _process_payload.setENVCODE("EAMS_TransFaAssetInfoSrv");
        _process_payload.setPERIODNAME("AUG-04");
        
        
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transfaassetinfosrv.SBFIFATransFaAssetInfoSrvProcessResponse _process__return = port.process(_process_payload);
        System.out.println("process.result.errorflag=" + _process__return.getERRORFLAG());
        System.out.println("process.result.errormessage=" + _process__return.getERRORMESSAGE());
        System.out.println("process.result.instanceid=" + _process__return.getINSTANCEID());


        }

        System.exit(0);
    }

}
