
/*
 * 
 */

package com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetdeprecationsrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Oct 15 15:41:00 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TDPageInquiryAssetDeprecationSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDPageInquiryAssetDeprecationSrv/2.0/SB_FI_FA_TDPageInquiryAssetDeprecationSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv") 
public class SBFIFATDPageInquiryAssetDeprecationSrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv", "SB_FI_FA_TDPageInquiryAssetDeprecationSrv");
    public final static QName SBFIFAPageInquiryAssetDeprecationSrvPort = new QName("http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv", "SB_FI_FA_PageInquiryAssetDeprecationSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDPageInquiryAssetDeprecationSrv/2.0/SB_FI_FA_TDPageInquiryAssetDeprecationSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDPageInquiryAssetDeprecationSrv/2.0/SB_FI_FA_TDPageInquiryAssetDeprecationSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATDPageInquiryAssetDeprecationSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATDPageInquiryAssetDeprecationSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATDPageInquiryAssetDeprecationSrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAPageInquiryAssetDeprecationSrv
     */
    @WebEndpoint(name = "SB_FI_FA_PageInquiryAssetDeprecationSrvPort")
    public SBFIFAPageInquiryAssetDeprecationSrv getSBFIFAPageInquiryAssetDeprecationSrvPort() {
        return super.getPort(SBFIFAPageInquiryAssetDeprecationSrvPort, SBFIFAPageInquiryAssetDeprecationSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAPageInquiryAssetDeprecationSrv
     */
    @WebEndpoint(name = "SB_FI_FA_PageInquiryAssetDeprecationSrvPort")
    public SBFIFAPageInquiryAssetDeprecationSrv getSBFIFAPageInquiryAssetDeprecationSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAPageInquiryAssetDeprecationSrvPort, SBFIFAPageInquiryAssetDeprecationSrv.class, features);
    }

}
