package com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetdeprecationsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Oct 15 15:41:00 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv", name = "SB_FI_FA_PageInquiryAssetDeprecationSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFAPageInquiryAssetDeprecationSrv {

    @WebResult(name = "InquiryAssetDeprecationSrvResponse", targetNamespace = "http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv", partName = "payload")
    @WebMethod(action = "process")
    public InquiryAssetDeprecationSrvResponse process(
        @WebParam(partName = "payload", name = "InquiryAssetDeprecationSrvRequest", targetNamespace = "http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv")
        InquiryAssetDeprecationSrvRequest payload
    );
}
