package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_pageinquiryassetlocationsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 16:57:28 CST 2011
 * Generated source version: 2.1.4
 * date:2011-09-08
 * DES: 查询资产地点接口(读出)
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetLocationSrv", name = "SB_FI_FA_PageInquiryAssetLocationSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFAPageInquiryAssetLocationSrv {

    @WebResult(name = "PageInquiryAssetLocationSrvResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetLocationSrv", partName = "payload")
    @WebMethod(action = "process")
    public PageInquiryAssetLocationSrvResponse process(
        @WebParam(partName = "payload", name = "PageInquiryAssetLocationSrvRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetLocationSrv")
        PageInquiryAssetLocationSrvRequest payload
    );
}
