package com.sino.ams.newasset.constant;

import com.sino.ams.constant.CustMessageKey;
import com.sino.base.constant.message.MsgKeyConstant;

/**
 * <p>Title: SinoEAM</p>
 * <p>Description: 山西移动实物资产管理系统</p>
 * <p>Copyright: 北京思诺博信息技术有限公司版权所有Copyright (c) 2007</p>
 * <p>Company: 北京思诺博信息技术有限公司</p>
 * @author 唐明胜
 * @version 1.0
 */
public interface AssetsMessageKeys extends CustMessageKey, MsgKeyConstant {
	String PRIVI_DELETE_SUCCESS = "PRIVI_DELETE_SUCCESS";
	String PRIVI_DELETE_FAILURE = "PRIVI_DELETE_FAILURE";
	String ASS_PRIVI_SAVE_SUCCESS = "ASS_PRIVI_SAVE_SUCCESS";
	String ASS_PRIVI_SAVE_FAILURE = "ASS_PRIVI_SAVE_FAILURE";

	String ASSETS_TRANSFER_SUCCESS = "ASSETS_TRANSFER_SUCCESS";
	String ASSETS_TRANSFER_FAILURE = "ASSETS_TRANSFER_FAILURE";
	String ASSETS_DISCARD_SUCCESS = "ASSETS_DISCARD_SUCCESS";
	String ASSETS_ALL_RESERVED = "ASSETS_ALL_RESERVED";
	String ASSETS_DISCARD_FAILURE = "ASSETS_DISCARD_FAILURE";
	String ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
	String ORDER_CANCEL_FAILURE = "ORDER_CANCEL_FAILURE";
	
	String ASSETS_WASTEFORECAST_SUCCESS = "ASSETS_WASTEFORECAST_SUCCESS";
	String ASSETS_WASTEFORECAST_FAILURE = "ASSETS_WASTEFORECAST_FAILURE";

	String ASSETS_CLEAR_SUCCESS = "ASSETS_CLEAR_SUCCESS";
	String ASSETS_CLEAR_FAILURE = "ASSETS_CLEAR_FAILURE";

	String ASSETS_FREE_SUCCESS = "ASSETS_FREE_SUCCESS";
	String ASSETS_FREE_FAILURE = "ASSETS_FREE_FAILURE";
	
	String ASSETS_SHARE_SUCCESS = "ASSETS_SHARE_SUCCESS";
	String ASSETS_SHARE_FAILURE = "ASSETS_SHARE_FAILURE";

	String ASSETS_SUB_SUCCESS = "ASSETS_SUB_SUCCESS";
	String ASSETS_SUB_FAILURE = "ASSETS_SUB_FAILURE";
	
	String ASSETS_REPAIR_SUCCESS = "ASSETS_REPAIR_SUCCESS";
    String ASSETS_REPAIR_FAILURE = "ASSETS_REPAIR_FAILURE";


	String NOT_CHECK_DEPT = "NOT_CHECK_DEPT";
	String NOT_CHECK_COMPANY = "NOT_CHECK_COMPANY";
	String NOT_DEPT_MANAGER = "NOT_DEPT_MANAGER";
	String NOT_COMPANY_MANAGER = "NOT_COMPANY_MANAGER";
	String NOT_PROVINCE_MANAGER = "NOT_PROVINCE_MANAGER";
	String RCV_ASSETS_SUCCESS = "RCV_ASSETS_SUCCESS";
	String RCV_ASSETS_FAILURE = "RCV_ASSETS_FAILURE";
	String ASN_ASSETS_SUCCESS = "ASN_ASSETS_SUCCESS";
	String ASN_ASSETS_FAILURE = "ASN_ASSETS_FAILURE";

	String CFM_ASSETS_SUCCESS = "CFM_ASSETS_SUCCESS";
	String CFM_ASSETS_FAILURE = "CFM_ASSETS_FAILURE";
	String APPROVE_INVALID = "APPROVE_INVALID";
	String RCV_INVALID = "RCV_INVALID";

	String SAVE_CHECK_SUCCESS = "SAVE_CHECK_SUCCESS";
	String SAVE_CHECK_FAILURE = "SAVE_CHECK_FAILURE";
	String SUBMIT_CHECK_SUCCESS = "SUBMIT_CHECK_SUCCESS";
	String SUBMIT_CHECK_FAILURE = "SUBMIT_CHECK_FAILURE";
	String DIST_ORDER_SUCCESS = "DIST_ORDER_SUCCESS";
	String DIST_ORDER_FAILURE = "DIST_ORDER_FAILURE";
	String ARCH_ORDER_SUCCESS = "ARCH_ORDER_SUCCESS";
	String ARCH_ORDER_FAILURE = "ARCH_ORDER_FAILURE";

	String PASS_ORDER_SUCCESS = "PASS_ORDER_SUCCESS";
	String PASS_ORDER_FAILURE = "PASS_ORDER_FAILURE";
	String REJECT_ORDER_SUCCESS = "REJECT_ORDER_SUCCESS";
	String REJECT_ORDER_FAILURE = "REJECT_ORDER_FAILURE";

	String INVALID_OPERATE = "INVALID_OPERATE";
	String HAS_PREVIOUS_ORDER = "HAS_PREVIOUS_ORDER";
	String COMM_QRY_CUST_SUCCESS = "COMM_QRY_CUST_SUCCESS";
	String COMM_QRY_CUST_FAILURE = "COMM_QRY_CUST_FAILURE";
	String NOT_DEFINE_FIELDS = "NOT_DEFINE_FIELDS";
	String ONLY_COMPMGR_PRIVI = "ONLY_COMPMGR_PRIVI";
	String ONLY_DEPTMGR_PRIVI = "ONLY_DEPTMGR_PRIVI";
	String HAS_NO_MIS_NUMBER = "HAS_NO_MIS_NUMBER";
	String HAS_NO_OPERATE_PRIVI = "HAS_NO_OPERATE_PRIVI";
	String RCV_AUTO_CREATE = "RCV_AUTO_CREATE";
	String RCVORDER_SUBMIT_SUCCESS = "RCVORDER_SUBMIT_SUCCESS";
	String RCVORDER_SUBMIT_FAILURE = "RCVORDER_SUBMIT_FAILURE";
	String NO_SPEC_GROUPS = "NO_SPEC_GROUPS";
	String NO_SPEC_ROLES = "NO_SPEC_ROLES";
	String ITEM_UPDATE_SUCCESS = "ITEM_UPDATE_SUCCESS";
	String ITEM_UPDATE_FAILURE = "ITEM_UPDATE_FAILURE";

	String SUBMIT_DATA_INVALID = "SUBMIT_DATA_INVALID";

	String READ_HOUSE_SUCCESS = "READ_HOUSE_SUCCESS";
	String READ_HOUSE_FAILURE = "READ_HOUSE_FAILURE";
	
	String SPACIAL_ASSETS_TRANSFER_SUCCESS = "SPACIAL_ASSETS_TRANSFER_SUCCESS";
	String SPACIAL_ASSETS_TRANSFER_FAILURE = "SPACIAL_ASSETS_TRANSFER_FAILURE";
	
	String WORKORDER_DEFINE_SUCCESS = "WORKORDER_DEFINE_SUCCESS";
	String WORKORDER_DEFINE_FAILURE = "WORKORDER_DEFINE_FAILURE";
	
	String ASSETS_DEVALUE_SUCCESS = "ASSETS_DEVALUE_SUCCESS";
	String ASSETS_DEVALUE_FAILURE = "ASSETS_DEVALUE_FAILURE";
}
