
package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_pageinquiryassetdeprecationsrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Oct 14 16:59:56 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIFAPageInquiryAssetDeprecationSrv_SBFIFAPageInquiryAssetDeprecationSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/common/fi/SB_FI_FA_PageInquiryAssetDeprecationSrv", "SB_FI_FA_PageInquiryAssetDeprecationSrv");

    private SBFIFAPageInquiryAssetDeprecationSrv_SBFIFAPageInquiryAssetDeprecationSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIFAPageInquiryAssetDeprecationSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIFAPageInquiryAssetDeprecationSrv_Service ss = new SBFIFAPageInquiryAssetDeprecationSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFAPageInquiryAssetDeprecationSrv port = ss.getSBFIFAPageInquiryAssetDeprecationSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_pageinquiryassetdeprecationsrv.InquiryAssetDeprecationSrvRequest _process_payload = null;
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_pageinquiryassetdeprecationsrv.InquiryAssetDeprecationSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
