package com.sino.soa.td.srv.transTaskInfo.srv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
import com.sino.base.util.StrUtil;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import com.sino.soa.common.SrvReturnMessage;
import com.sino.soa.util.XMLGregorianCalendarUtil;
import com.sino.soa.td.eip.sc.pa.sb_sc_pa_transtaskinfosrv.SBSCPATDTransTaskInfoSrv;  //SBSCPATransTaskInfoSrv_Service;
import com.sino.soa.td.eip.sc.pa.sb_sc_pa_transtaskinfosrv.SBSCPATransTaskInfoSrv; // .SBSCPATransTaskInfoSrv;
import com.sino.soa.td.eip.sc.pa.sb_sc_pa_transtaskinfosrv.SBSCPATransTaskInfoSrvProcessRequest; //.SBSCPATransTaskInfoSrvProcessRequest;
import com.sino.soa.td.eip.sc.pa.sb_sc_pa_transtaskinfosrv.SBSCPATransTaskInfoSrvProcessResponse; //.SBSCPATransTaskInfoSrvProcessResponse;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.1.4
 *  2011-10-12
 * Generated source version: 2.1.4
 * MIS系统项目任务信息(ODI)_TD 
 */

public final class TDTransTaskInfoSrv {
    private SrvReturnMessage returnMessage = new SrvReturnMessage();
    private String envCode="";          //环境代码
    private String projectNum = "";     //项目编号
    private String taskNum = "";        //任务编号
    private String stratLastUpdateDate = "";   //最后更新开始日期
    private String endLastUpdateDate = "";     //最后更新结束日期
    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_SC_PA_TransTaskInfoSrv", "SB_SC_PA_TDTransTaskInfoSrv");

    public TDTransTaskInfoSrv() {
    }

    public void excute() throws Exception {
    
        URL wsdlURL = SBSCPATDTransTaskInfoSrv.WSDL_LOCATION;
        SBSCPATDTransTaskInfoSrv ss = new SBSCPATDTransTaskInfoSrv(wsdlURL, SERVICE_NAME);
        SBSCPATransTaskInfoSrv port = ss.getSBSCPATransTaskInfoSrvPort();

        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();

        httpClientPolicy.setConnectionTimeout(5400000);//连接时间
        httpClientPolicy.setReceiveTimeout(5400000);//接收时间
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);

        {
            System.out.println("SB_FI_FA_TransAssetDistributionSrv Invoking process...");
            SBSCPATransTaskInfoSrvProcessRequest _process_payload = null;
            _process_payload = new SBSCPATransTaskInfoSrvProcessRequest();
            _process_payload.setENVCODE(getEnvCode());
            _process_payload.setPROJECTNUM(this.projectNum);
            _process_payload.setTASKNUM(this.taskNum);
            
            _process_payload.setENDLASTUPDATEDATE(XMLGregorianCalendarUtil.getXMLGregorianCalendar(this.endLastUpdateDate));
            _process_payload.setSTARTLASTUPDATEDATE(XMLGregorianCalendarUtil.getXMLGregorianCalendar(this.stratLastUpdateDate));
            SBSCPATransTaskInfoSrvProcessResponse _process__return = port.process(_process_payload);
            //System.out.println("process.result=" + _process__return.getINSTANCEID() + "||" + _process__return.getERRORFLAG() + "||" + _process__return.getERRORMESSAGE());
            returnMessage.setErrorFlag(StrUtil.nullToString(_process__return.getERRORFLAG()));
            returnMessage.setErrorMessage(_process__return.getERRORMESSAGE());
            System.out.println("是否成功：---------" + returnMessage.getErrorFlag());
            System.out.println("错误信息：---------" + returnMessage.getErrorMessage());
        }
    }

    public static void main(String[] args) throws Exception {
    	TDTransTaskInfoSrv srv = new TDTransTaskInfoSrv();
    	srv.setEnvCode("EAMS_TDTransTaskInfoSrv");
    	srv.setProjectNum("T-B41001");
    	srv.setTaskNum("10");
    	srv.setStratLastUpdateDate("2010-05-19");
    	srv.setEndLastUpdateDate("2010-05-19");
       srv.excute();

        System.exit(0);
    }

    /**
     * @return the returnMessage
     */
    public SrvReturnMessage getReturnMessage() {
        return returnMessage;
    }

    /**
     * @param returnMessage the returnMessage to set
     */
    public void setReturnMessage(SrvReturnMessage returnMessage) {
        this.returnMessage = returnMessage;
    }

    public String getEnvCode() {
        return envCode;
    }

    public void setEnvCode(String envCode) {
        this.envCode = envCode;
    }

    /**
     * @return the stratLastUpdateDate
     */
    public String getStratLastUpdateDate() {
        return stratLastUpdateDate;
    }

    /**
     * @param stratLastUpdateDate the stratLastUpdateDate to set
     */
    public void setStratLastUpdateDate(String stratLastUpdateDate) {
        this.stratLastUpdateDate = stratLastUpdateDate;
    }

    /**
     * @return the endLastUpdateDate
     */
    public String getEndLastUpdateDate() {
        return endLastUpdateDate;
    }

    /**
     * @param endLastUpdateDate the endLastUpdateDate to set
     */
    public void setEndLastUpdateDate(String endLastUpdateDate) {
        this.endLastUpdateDate = endLastUpdateDate;
    }

	public String getProjectNum() {
		return projectNum;
	}

	public void setProjectNum(String projectNum) {
		this.projectNum = projectNum;
	}

	public String getTaskNum() {
		return taskNum;
	}

	public void setTaskNum(String taskNum) {
		this.taskNum = taskNum;
	}


}