package com.sino.soa.mis.srv.assetsinfoupdate.srv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.sino.base.util.StrUtil;
import com.sino.base.exception.CalendarException;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import com.sino.soa.common.SrvReturnMessage;
import com.sino.soa.util.XMLGregorianCalendarUtil;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrv;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrvProcessRequest;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrv_Service;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.SBFIFATransAssetHeaderInfoSrvProcessResponse;

import javax.xml.namespace.QName;
import javax.xml.datatype.DatatypeConfigurationException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sun May 10 16:50:30 CST 2011
 * Generated source version: 2.1.4
 * 功能： 查询资产头基本信息_非TD(ODI)
 */

public final class TransAssetHeaderInfoSrv {

    private SrvReturnMessage returnMessage = new SrvReturnMessage();

    private String envCode = "";
    private String bookTypeCode = "";
    private String startLastUpdateDate = "";
    private String endLastUpdateDate = "";

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetHeaderInfoSrv", "SB_FI_FA_TransAssetHeaderInfoSrv");

    public TransAssetHeaderInfoSrv() {

    }

    public void excute() throws CalendarException, DatatypeConfigurationException {
        URL wsdlURL = SBFIFATransAssetHeaderInfoSrv_Service.WSDL_LOCATION;

        SBFIFATransAssetHeaderInfoSrv_Service ss = new SBFIFATransAssetHeaderInfoSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFATransAssetHeaderInfoSrv port = ss.getSBFIFATransAssetHeaderInfoSrvPort();

        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();

        httpClientPolicy.setConnectionTimeout(5400000);//连接时间
        httpClientPolicy.setReceiveTimeout(5400000);//接收时间
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);
        {
            System.out.println("SB_FI_FA_TransAssetHeaderInfoSrv Invoking process...");
            SBFIFATransAssetHeaderInfoSrvProcessRequest _process_payload = null;
            _process_payload = new SBFIFATransAssetHeaderInfoSrvProcessRequest();
            _process_payload.setBOOKTYPECODE(bookTypeCode);
            _process_payload.setENVCODE(envCode);
            _process_payload.setSTARTLASTUPDATEDATE(XMLGregorianCalendarUtil.getXMLGregorianCalendar(startLastUpdateDate));
            _process_payload.setENDLASTUPDATEDATE(XMLGregorianCalendarUtil.getXMLGregorianCalendar(endLastUpdateDate));
            SBFIFATransAssetHeaderInfoSrvProcessResponse _process__return = port.process(_process_payload);
            returnMessage.setErrorFlag(StrUtil.nullToString(_process__return.getERRORFLAG()));
            returnMessage.setErrorMessage(_process__return.getERRORMESSAGE());
            System.out.println("是否成功：---------"+returnMessage.getErrorFlag());
            System.out.println("错误信息：---------"+returnMessage.getErrorMessage());


        }

    }

    /**
     * @return the bookTypeCode
     */
    public String getBookTypeCode() {
        return bookTypeCode;
    }

    /**
     * @param bookTypeCode the bookTypeCode to set
     */
    public void setBookTypeCode(String bookTypeCode) {
        this.bookTypeCode = bookTypeCode;
    }

    /**
     * @return the endLastUpdateDate
     */
    public String getEndLastUpdateDate() {
        return endLastUpdateDate;
    }

    /**
     * @param endLastUpdateDate the endLastUpdateDate to set
     */
    public void setEndLastUpdateDate(String endLastUpdateDate) {
        this.endLastUpdateDate = endLastUpdateDate;
    }

    /**
     * @return the envCode
     */
    public String getEnvCode() {
        return envCode;
    }

    /**
     * @param envCode the envCode to set
     */
    public void setEnvCode(String envCode) {
        this.envCode = envCode;
    }

    /**
     * @return the startLastUpdateDate
     */
    public String getStartLastUpdateDate() {
        return startLastUpdateDate;
    }

    /**
     * @param startLastUpdateDate the startLastUpdateDate to set
     */
    public void setStartLastUpdateDate(String startLastUpdateDate) {
        this.startLastUpdateDate = startLastUpdateDate;
    }

    /**
     * @return the returnMessage
     */
    public SrvReturnMessage getReturnMessage() {
        return returnMessage;
    }

    /**
     * @param returnMessage the returnMessage to set
     */
    public void setReturnMessage(SrvReturnMessage returnMessage) {
        this.returnMessage = returnMessage;
    }

    public static void main(String args[]) throws Exception {
        TransAssetHeaderInfoSrv srv = new TransAssetHeaderInfoSrv();
        srv.setEnvCode("EAMS_TransAssetHeaderInfoSrv"); //TransAssetHeaderInfoSrv
        srv.setBookTypeCode("SXMC_FA_4110"); //SXMC_FA_4187
		//srv.setStartLastUpdateDate("1999-01-01");
		//srv.setEndLastUpdateDate("2009-10-30");
        srv.excute();
    }

}
