
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetcustdetailsrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 13 14:07:30 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TransAssetCustDetailSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetCustDetailSrv/1.0/SB_FI_FA_TransAssetCustDetailSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetCustDetailSrv") 
public class SBFIFATransAssetCustDetailSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetCustDetailSrv", "SB_FI_FA_TransAssetCustDetailSrv");
    public final static QName SBFIFATransAssetCustDetailSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetCustDetailSrv", "SB_FI_FA_TransAssetCustDetailSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetCustDetailSrv/1.0/SB_FI_FA_TransAssetCustDetailSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetCustDetailSrv/1.0/SB_FI_FA_TransAssetCustDetailSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATransAssetCustDetailSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATransAssetCustDetailSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATransAssetCustDetailSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFATransAssetCustDetailSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransAssetCustDetailSrvPort")
    public SBFIFATransAssetCustDetailSrv getSBFIFATransAssetCustDetailSrvPort() {
        return super.getPort(SBFIFATransAssetCustDetailSrvPort, SBFIFATransAssetCustDetailSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFATransAssetCustDetailSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransAssetCustDetailSrvPort")
    public SBFIFATransAssetCustDetailSrv getSBFIFATransAssetCustDetailSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFATransAssetCustDetailSrvPort, SBFIFATransAssetCustDetailSrv.class, features);
    }

}
