
package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetcustdetailsrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 13 14:07:30 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIFATransAssetCustDetailSrv_SBFIFATransAssetCustDetailSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetCustDetailSrv", "SB_FI_FA_TransAssetCustDetailSrv");

    private SBFIFATransAssetCustDetailSrv_SBFIFATransAssetCustDetailSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIFATransAssetCustDetailSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIFATransAssetCustDetailSrv_Service ss = new SBFIFATransAssetCustDetailSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFATransAssetCustDetailSrv port = ss.getSBFIFATransAssetCustDetailSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetcustdetailsrv.SBFIFATransAssetCustDetailSrvProcessRequest _process_payload = null;
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetcustdetailsrv.SBFIFATransAssetCustDetailSrvProcessResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
