
package com.sino.soa.mis.eip.hr.hr.sb_hr_hr_inquiryorgstructuresrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sun Oct 16 18:20:54 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBHRHRInquiryOrgStructureSrv_SBHRHRInquiryOrgStructureSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/hr/SB_HR_HR_InquiryOrgStructureSrv", "SB_HR_HR_InquiryOrgStructureSrv");

    private SBHRHRInquiryOrgStructureSrv_SBHRHRInquiryOrgStructureSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBHRHRInquiryOrgStructureSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBHRHRInquiryOrgStructureSrv_Service ss = new SBHRHRInquiryOrgStructureSrv_Service(wsdlURL, SERVICE_NAME);
        SBHRHRInquiryOrgStructureSrv port = ss.getSBHRHRInquiryOrgStructureSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.hr.hr.sb_hr_hr_inquiryorgstructuresrv.InquiryOrgStructureSrvRequest _process_payload = null;
        com.sino.soa.mis.eip.hr.hr.sb_hr_hr_inquiryorgstructuresrv.InquiryOrgStructureSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
