package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transretiredassetdetailsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:26:05 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransRetiredAssetDetailSrv", name = "SB_FI_FA_TransRetiredAssetDetailSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFATransRetiredAssetDetailSrv {

    @WebResult(name = "SB_FI_FA_TransRetiredAssetDetailSrvProcessResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransRetiredAssetDetailSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIFATransRetiredAssetDetailSrvProcessResponse process(
        @WebParam(partName = "payload", name = "SB_FI_FA_TransRetiredAssetDetailSrvProcessRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransRetiredAssetDetailSrv")
        SBFIFATransRetiredAssetDetailSrvProcessRequest payload
    );
}
