
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transretiredassetdetailsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:26:05 CST 2011
 * Generated source version: 2.1.4
 * 查询资产报废信息_非TD(_ODI)
 */


@WebServiceClient(name = "SB_FI_FA_TransRetiredAssetDetailSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransRetiredAssetDetailSrv/1.0/SB_FI_FA_TransRetiredAssetDetailSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransRetiredAssetDetailSrv") 
public class SBFIFATransRetiredAssetDetailSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_TransRetiredAssetDetailSrv", "SB_FI_FA_TransRetiredAssetDetailSrv");
    public final static QName SBFIFATransRetiredAssetDetailSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_TransRetiredAssetDetailSrv", "SB_FI_FA_TransRetiredAssetDetailSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransRetiredAssetDetailSrv/1.0/SB_FI_FA_TransRetiredAssetDetailSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransRetiredAssetDetailSrv/1.0/SB_FI_FA_TransRetiredAssetDetailSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATransRetiredAssetDetailSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATransRetiredAssetDetailSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATransRetiredAssetDetailSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFATransRetiredAssetDetailSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransRetiredAssetDetailSrvPort")
    public SBFIFATransRetiredAssetDetailSrv getSBFIFATransRetiredAssetDetailSrvPort() {
        return super.getPort(SBFIFATransRetiredAssetDetailSrvPort, SBFIFATransRetiredAssetDetailSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFATransRetiredAssetDetailSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransRetiredAssetDetailSrvPort")
    public SBFIFATransRetiredAssetDetailSrv getSBFIFATransRetiredAssetDetailSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFATransRetiredAssetDetailSrvPort, SBFIFATransRetiredAssetDetailSrv.class, features);
    }

}
