
package com.sino.soa.mis.eip.sy.sy.sb_sy_sy_pageinquiryvsetvalueinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 14 10:46:57 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBSYSYPageInquiryVSetValueInfoSrv_SBSYSYPageInquiryVSetValueInfoSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/common/sy/SB_SY_SY_PageInquiryVSetValueInfoSrv", "SB_SY_SY_PageInquiryVSetValueInfoSrv");

    private SBSYSYPageInquiryVSetValueInfoSrv_SBSYSYPageInquiryVSetValueInfoSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBSYSYPageInquiryVSetValueInfoSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBSYSYPageInquiryVSetValueInfoSrv_Service ss = new SBSYSYPageInquiryVSetValueInfoSrv_Service(wsdlURL, SERVICE_NAME);
        SBSYSYPageInquiryVSetValueInfoSrv port = ss.getSBSYSYPageInquiryVSetValueInfoSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.sy.sy.sb_sy_sy_pageinquiryvsetvalueinfosrv.PageInquiryVSetValueInfoSrvRequest _process_payload = null;
        com.sino.soa.mis.eip.sy.sy.sb_sy_sy_pageinquiryvsetvalueinfosrv.PageInquiryVSetValueInfoSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
