
package com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetcategorysrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 11:31:16 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIFAPageInquiryAssetCategorySrv_SBFIFAPageInquiryAssetCategorySrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetCategorySrv", "SB_FI_FA_TDPageInquiryAssetCategorySrv");

    private SBFIFAPageInquiryAssetCategorySrv_SBFIFAPageInquiryAssetCategorySrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIFATDPageInquiryAssetCategorySrv.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIFATDPageInquiryAssetCategorySrv ss = new SBFIFATDPageInquiryAssetCategorySrv(wsdlURL, SERVICE_NAME);
        SBFIFAPageInquiryAssetCategorySrv port = ss.getSBFIFAPageInquiryAssetCategorySrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetcategorysrv.PageInquiryAssetCategorySrvRequest _process_payload = null;
        com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetcategorysrv.PageInquiryAssetCategorySrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
