
/*
 * 
 */

package com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetcategorysrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 11:31:16 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TDPageInquiryAssetCategorySrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDPageInquiryAssetCategorySrv/1.0/SB_FI_FA_TDPageInquiryAssetCategorySrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetCategorySrv") 
public class SBFIFATDPageInquiryAssetCategorySrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetCategorySrv", "SB_FI_FA_TDPageInquiryAssetCategorySrv");
    public final static QName SBFIFAPageInquiryAssetCategorySrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetCategorySrv", "SB_FI_FA_PageInquiryAssetCategorySrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDPageInquiryAssetCategorySrv/1.0/SB_FI_FA_TDPageInquiryAssetCategorySrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDPageInquiryAssetCategorySrv/1.0/SB_FI_FA_TDPageInquiryAssetCategorySrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATDPageInquiryAssetCategorySrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATDPageInquiryAssetCategorySrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATDPageInquiryAssetCategorySrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAPageInquiryAssetCategorySrv
     */
    @WebEndpoint(name = "SB_FI_FA_PageInquiryAssetCategorySrvPort")
    public SBFIFAPageInquiryAssetCategorySrv getSBFIFAPageInquiryAssetCategorySrvPort() {
        return super.getPort(SBFIFAPageInquiryAssetCategorySrvPort, SBFIFAPageInquiryAssetCategorySrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAPageInquiryAssetCategorySrv
     */
    @WebEndpoint(name = "SB_FI_FA_PageInquiryAssetCategorySrvPort")
    public SBFIFAPageInquiryAssetCategorySrv getSBFIFAPageInquiryAssetCategorySrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAPageInquiryAssetCategorySrvPort, SBFIFAPageInquiryAssetCategorySrv.class, features);
    }

}
