
/*
 * 
 */

package com.sino.soa.td.eip.fi.fa.sb_fi_fa_importassetlocationcombinationsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Oct 14 14:54:13 CST 2011
 * Generated source version: 2.1.4
 *  资产地点组合导入_TD
 */
 

@WebServiceClient(name = "SB_FI_FA_TDImportAssetLocationCombinationSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDImportAssetLocationCombinationSrv/1.0/SB_FI_FA_TDImportAssetLocationCombinationSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/SB_FI_FA_ImportAssetLocationCombinationSrv") 
public class SBFIFATDImportAssetLocationCombinationSrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/SB_FI_FA_ImportAssetLocationCombinationSrv", "SB_FI_FA_TDImportAssetLocationCombinationSrv");
    public final static QName SBFIFAImportAssetLocationCombinationSrvPort = new QName("http://eip.zte.com/SB_FI_FA_ImportAssetLocationCombinationSrv", "SB_FI_FA_ImportAssetLocationCombinationSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDImportAssetLocationCombinationSrv/1.0/SB_FI_FA_TDImportAssetLocationCombinationSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDImportAssetLocationCombinationSrv/1.0/SB_FI_FA_TDImportAssetLocationCombinationSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATDImportAssetLocationCombinationSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATDImportAssetLocationCombinationSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATDImportAssetLocationCombinationSrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAImportAssetLocationCombinationSrv
     */
    @WebEndpoint(name = "SB_FI_FA_ImportAssetLocationCombinationSrvPort")
    public SBFIFAImportAssetLocationCombinationSrv getSBFIFAImportAssetLocationCombinationSrvPort() {
        return super.getPort(SBFIFAImportAssetLocationCombinationSrvPort, SBFIFAImportAssetLocationCombinationSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAImportAssetLocationCombinationSrv
     */
    @WebEndpoint(name = "SB_FI_FA_ImportAssetLocationCombinationSrvPort")
    public SBFIFAImportAssetLocationCombinationSrv getSBFIFAImportAssetLocationCombinationSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAImportAssetLocationCombinationSrvPort, SBFIFAImportAssetLocationCombinationSrv.class, features);
    }

}
