package com.sino.soa.td.eip.fi.fa.sb_fi_fa_importassetlocationcombinationsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Oct 14 14:54:13 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/SB_FI_FA_ImportAssetLocationCombinationSrv", name = "SB_FI_FA_ImportAssetLocationCombinationSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFAImportAssetLocationCombinationSrv {

    @WebResult(name = "ImportAssetLocationCombinationSrvResponse", targetNamespace = "http://eip.zte.com/SB_FI_FA_ImportAssetLocationCombinationSrv", partName = "payload")
    @WebMethod(action = "process")
    public ImportAssetLocationCombinationSrvResponse process(
        @WebParam(partName = "payload", name = "ImportAssetLocationCombinationSrvRequest", targetNamespace = "http://eip.zte.com/SB_FI_FA_ImportAssetLocationCombinationSrv")
        ImportAssetLocationCombinationSrvRequest payload
    );
}
