package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sun Oct 16 22:16:18 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferInCompanySrv", name = "SB_FI_FA_CreateAssetTransferInCompanySrv")
@XmlSeeAlso({com.sino.soa.mis.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv.msgheader.ObjectFactory.class, com.sino.soa.mis.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv.importsrvresponse.ObjectFactory.class, com.sino.soa.mis.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv.createassettransferincompanysrv.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFACreateAssetTransferInCompanySrv {

    @WebResult(name = "CreateAssetTransferInCompanySrvResponse", targetNamespace = "http://eip.zte.com/common/fa/CreateAssetTransferInCompanySrv", partName = "payload")
    @WebMethod(action = "process")
    public com.sino.soa.mis.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv.importsrvresponse.ImportSrvResponse process(
        @WebParam(partName = "payload", name = "CreateAssetTransferInCompanySrvRequest", targetNamespace = "http://eip.zte.com/common/fa/CreateAssetTransferInCompanySrv")
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_createassettransferincompanysrv.createassettransferincompanysrv.CreateAssetTransferInCompanySrvRequest payload
    );
}
