
package com.sino.soa.mis.eip.sy.sy.sb_sy_sy_importvsetvalueinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 14 15:07:57 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBSYSYImportVSetValueInfoSrv_SBSYSYImportVSetValueInfoSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/SB_SY_SY_ImportVSetValueInfoSrv", "SB_SY_SY_ImportVSetValueInfoSrv");

    private SBSYSYImportVSetValueInfoSrv_SBSYSYImportVSetValueInfoSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBSYSYImportVSetValueInfoSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBSYSYImportVSetValueInfoSrv_Service ss = new SBSYSYImportVSetValueInfoSrv_Service(wsdlURL, SERVICE_NAME);
        SBSYSYImportVSetValueInfoSrv port = ss.getSBSYSYImportVSetValueInfoSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.sy.sy.sb_sy_sy_importvsetvalueinfosrv.ImportVSetValueInfoSrvRequest _process_payload = null;
        com.sino.soa.mis.eip.sy.sy.sb_sy_sy_importvsetvalueinfosrv.ImportVSetValueInfoSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
