package com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:48:55 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetHeaderInfoSrv", name = "SB_FI_FA_TransAssetHeaderInfoSrv")
@XmlSeeAlso({com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetheaderinfosrv.odi_variables.ObjectFactory.class,ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFATransAssetHeaderInfoSrv {

    @WebResult(name = "SB_FI_FA_TransAssetHeaderInfoSrvProcessResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetHeaderInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIFATransAssetHeaderInfoSrvProcessResponse process(
        @WebParam(partName = "payload", name = "SB_FI_FA_TransAssetHeaderInfoSrvProcessRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetHeaderInfoSrv")
        SBFIFATransAssetHeaderInfoSrvProcessRequest payload
    );
}
