
/*
 * 
 */

package com.sino.soa.mis.eip.sc.po.sb_sc_po_inquiryvendorinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Oct 12 21:07:20 CST 2011
 * Generated source version: 2.1.4
 *   查询供货商信息
 */


@WebServiceClient(name = "SB_SC_PO_InquiryVendorInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PO_InquiryVendorInfoSrv/1.1/SB_SC_PO_InquiryVendorInfoSrv?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/SB_SC_PO_InquiryVendorInfoSrv") 
public class SBSCPOInquiryVendorInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://xmlns.oracle.com/SB_SC_PO_InquiryVendorInfoSrv", "SB_SC_PO_InquiryVendorInfoSrv");
    public final static QName SBSCPOInquiryVendorInfoSrvPort = new QName("http://xmlns.oracle.com/SB_SC_PO_InquiryVendorInfoSrv", "SB_SC_PO_InquiryVendorInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PO_InquiryVendorInfoSrv/1.1/SB_SC_PO_InquiryVendorInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PO_InquiryVendorInfoSrv/1.1/SB_SC_PO_InquiryVendorInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBSCPOInquiryVendorInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBSCPOInquiryVendorInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBSCPOInquiryVendorInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBSCPOInquiryVendorInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PO_InquiryVendorInfoSrvPort")
    public SBSCPOInquiryVendorInfoSrv getSBSCPOInquiryVendorInfoSrvPort() {
        return super.getPort(SBSCPOInquiryVendorInfoSrvPort, SBSCPOInquiryVendorInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBSCPOInquiryVendorInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PO_InquiryVendorInfoSrvPort")
    public SBSCPOInquiryVendorInfoSrv getSBSCPOInquiryVendorInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBSCPOInquiryVendorInfoSrvPort, SBSCPOInquiryVendorInfoSrv.class, features);
    }

}
