package com.sino.soa.td.eip.sy.sy.sb_sy_sy_importvsetvalueinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 14 15:37:06 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://xmlns.oracle.com/SB_SY_SY_ImportVSetValueInfoSrv", name = "SB_SY_SY_ImportVSetValueInfoSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBSYSYImportVSetValueInfoSrv {

    @WebResult(name = "ImportVSetValueInfoSrvResponse", targetNamespace = "http://xmlns.oracle.com/SB_SY_SY_ImportVSetValueInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public ImportVSetValueInfoSrvResponse process(
        @WebParam(partName = "payload", name = "ImportVSetValueInfoSrvRequest", targetNamespace = "http://xmlns.oracle.com/SB_SY_SY_ImportVSetValueInfoSrv")
        ImportVSetValueInfoSrvRequest payload
    );
}
