
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:24:39 CST 2011
 * Generated source version: 2.1.4
 * 查询转资物料清单_非TD(ODI) 
 */


@WebServiceClient(name = "SB_FI_FA_TransMetaCustDetailSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransMetaCustDetailSrv/1.0/SB_FI_FA_TransMetaCustDetailSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv") 
public class SBFIFATransMetaCustDetailSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv", "SB_FI_FA_TransMetaCustDetailSrv");
    public final static QName SBFIFATransMetaCustDetailSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv", "SB_FI_FA_TransMetaCustDetailSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransMetaCustDetailSrv/1.0/SB_FI_FA_TransMetaCustDetailSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransMetaCustDetailSrv/1.0/SB_FI_FA_TransMetaCustDetailSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATransMetaCustDetailSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATransMetaCustDetailSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATransMetaCustDetailSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFATransMetaCustDetailSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransMetaCustDetailSrvPort")
    public SBFIFATransMetaCustDetailSrv getSBFIFATransMetaCustDetailSrvPort() {
        return super.getPort(SBFIFATransMetaCustDetailSrvPort, SBFIFATransMetaCustDetailSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFATransMetaCustDetailSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransMetaCustDetailSrvPort")
    public SBFIFATransMetaCustDetailSrv getSBFIFATransMetaCustDetailSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFATransMetaCustDetailSrvPort, SBFIFATransMetaCustDetailSrv.class, features);
    }

}
