package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:24:39 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv", name = "SB_FI_FA_TransMetaCustDetailSrv")
@XmlSeeAlso({ObjectFactory.class, com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.odi_variables.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFATransMetaCustDetailSrv {

    @WebResult(name = "SB_FI_FA_TransMetaCustDetailSrvProcessResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIFATransMetaCustDetailSrvProcessResponse process(
        @WebParam(partName = "payload", name = "SB_FI_FA_TransMetaCustDetailSrvProcessRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv")
        SBFIFATransMetaCustDetailSrvProcessRequest payload
    );
}
