
package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:24:39 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIFATransMetaCustDetailSrv_SBFIFATransMetaCustDetailSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv", "SB_FI_FA_TransMetaCustDetailSrv");

    private SBFIFATransMetaCustDetailSrv_SBFIFATransMetaCustDetailSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIFATransMetaCustDetailSrv_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIFATransMetaCustDetailSrv_Service ss = new SBFIFATransMetaCustDetailSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFATransMetaCustDetailSrv port = ss.getSBFIFATransMetaCustDetailSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.SBFIFATransMetaCustDetailSrvProcessRequest _process_payload = null;
        com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.SBFIFATransMetaCustDetailSrvProcessResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
