
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_importassetretirmentsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 18:48:07 CST 2011
 * Generated source version: 2.1.4
 * DSC:资产报废接口(2011-09-08)
 */

@WebServiceClient(name = "SB_FI_FA_ImportAssetRetirmentSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_ImportAssetRetirmentSrv/1.0/SB_FI_FA_ImportAssetRetirmentSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/SB_FI_FA_ImportAssetRetirmentSrv") 
public class SBFIFAImportAssetRetirmentSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/SB_FI_FA_ImportAssetRetirmentSrv", "SB_FI_FA_ImportAssetRetirmentSrv");
    public final static QName SBFIFAImportAssetRetirmentSrvPort = new QName("http://eip.zte.com/SB_FI_FA_ImportAssetRetirmentSrv", "SB_FI_FA_ImportAssetRetirmentSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_ImportAssetRetirmentSrv/1.0/SB_FI_FA_ImportAssetRetirmentSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_ImportAssetRetirmentSrv/1.0/SB_FI_FA_ImportAssetRetirmentSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFAImportAssetRetirmentSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFAImportAssetRetirmentSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFAImportAssetRetirmentSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAImportAssetRetirmentSrv
     */
    @WebEndpoint(name = "SB_FI_FA_ImportAssetRetirmentSrvPort")
    public SBFIFAImportAssetRetirmentSrv getSBFIFAImportAssetRetirmentSrvPort() {
        return super.getPort(SBFIFAImportAssetRetirmentSrvPort, SBFIFAImportAssetRetirmentSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAImportAssetRetirmentSrv
     */
    @WebEndpoint(name = "SB_FI_FA_ImportAssetRetirmentSrvPort")
    public SBFIFAImportAssetRetirmentSrv getSBFIFAImportAssetRetirmentSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAImportAssetRetirmentSrvPort, SBFIFAImportAssetRetirmentSrv.class, features);
    }

}
