package com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Sep 08 11:38:49 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://xmlns.oracle.com/SB_HR_HR_InquiryEmpBaseInfoSrv", name = "SB_HR_HR_InquiryEmpBaseInfoSrv")
@XmlSeeAlso({com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv.pcbpel.adapter.db.empbaseinfosrv.ObjectFactory.class, com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBHRHRInquiryEmpBaseInfoSrv {

    @WebResult(name = "InquiryEmpBaseInfoSrvResponse", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/EmpBaseInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv.pcbpel.adapter.db.empbaseinfosrv.InquiryEmpBaseInfoSrvResponse process(
        @WebParam(partName = "payload", name = "InquiryEmpBaseInfoSrvRequest", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/EmpBaseInfoSrv")
        com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv.pcbpel.adapter.db.empbaseinfosrv.InquiryEmpBaseInfoSrvRequest payload
    );
}
