
package com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Sep 08 11:38:49 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBHRHRInquiryEmpBaseInfoSrv_SBHRHRInquiryEmpBaseInfoSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/SB_HR_HR_InquiryEmpBaseInfoSrv", "SB_HR_HR_TDInquiryEmpBaseInfoSrv");

    private SBHRHRInquiryEmpBaseInfoSrv_SBHRHRInquiryEmpBaseInfoSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBHRHRTDInquiryEmpBaseInfoSrv.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBHRHRTDInquiryEmpBaseInfoSrv ss = new SBHRHRTDInquiryEmpBaseInfoSrv(wsdlURL, SERVICE_NAME);
        SBHRHRInquiryEmpBaseInfoSrv port = ss.getSBHRHRInquiryEmpBaseInfoSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv.pcbpel.adapter.db.empbaseinfosrv.InquiryEmpBaseInfoSrvRequest _process_payload = null;
        com.sino.soa.td.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv.pcbpel.adapter.db.empbaseinfosrv.InquiryEmpBaseInfoSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
