
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_dealprojectdiversitychecksrv;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.sino.soa.common.SOAConstant;


/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Oct 15 21:03:21 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_PageInquiryAssetCustDetailSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_DealProjectDiversityCheckSrv/2.0/SB_FI_FA_DealProjectDiversityCheckSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_DealProjectDiversityCheckSrv") 
public class DealProjectDiversityCheckSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetCustDetailSrv", "SB_FI_FA_PageInquiryAssetCustDetailSrv");
    public final static QName SBFIFADealProjectDiversityCheckSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_DealProjectDiversityCheckSrv", "SB_FI_FA_DealProjectDiversityCheckSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_DealProjectDiversityCheckSrv/2.0/SB_FI_FA_DealProjectDiversityCheckSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_DealProjectDiversityCheckSrv/2.0/SB_FI_FA_DealProjectDiversityCheckSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DealProjectDiversityCheckSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DealProjectDiversityCheckSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DealProjectDiversityCheckSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * @return
     *     returns SBFIFADealProjectDiversityCheckSrv
     */
    @WebEndpoint(name = "SB_FI_FA_DealProjectDiversityCheckSrvPort")
    public SBFIFADealProjectDiversityCheckSrv getSBFIFADealProjectDiversityCheckSrvPort() {
        return super.getPort(SBFIFADealProjectDiversityCheckSrvPort, SBFIFADealProjectDiversityCheckSrv.class);
    }

    /**
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFADealProjectDiversityCheckSrv
     */
    @WebEndpoint(name = "SB_FI_FA_DealProjectDiversityCheckSrvPort")
    public SBFIFADealProjectDiversityCheckSrv getSBFIFADealProjectDiversityCheckSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFADealProjectDiversityCheckSrvPort, SBFIFADealProjectDiversityCheckSrv.class, features);
    }
    
}
