package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_dealprojectdiversitychecksrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Oct 15 21:03:21 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_DealProjectDiversityCheckSrv", name = "SB_FI_FA_DealProjectDiversityCheckSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFADealProjectDiversityCheckSrv {

    @WebResult(name = "DealProjectDiversityCheckSrvResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_DealProjectDiversityCheckSrv", partName = "payload")
    @WebMethod(action = "process")
    public DealProjectDiversityCheckSrvResponse process(
        @WebParam(partName = "payload", name = "DealProjectDiversityCheckSrvRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_DealProjectDiversityCheckSrv")
        DealProjectDiversityCheckSrvRequest payload
    );
}
