package com.sino.soa.mis.srv.assetretire.srv;

import com.sino.base.exception.CalendarException;
import com.sino.base.util.StrUtil;
import com.sino.soa.common.SrvReturnMessage;
import com.sino.soa.util.XMLGregorianCalendarUtil;
//import srv.fi.fa.sb_fi_fa_importassetretirmentsrv.*;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_importassetretirmentsrv.*;
import com.sino.soa.mis.srv.AssetPeriodStatus.dto.SrvAssetPeriodStatusDTO;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.namespace.QName;
import java.math.BigDecimal;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon May 11 15:27:59 CST 2009
 * Generated source version: 2.1.4
 * DSC: 资产报废接口 实现类
 */

public final class ImportAssetRetirmentSrv {

    private List<ImportAssetRetirmentSrvInputItem> srvInputItems = null;
    private SrvReturnMessage returnMessage=new SrvReturnMessage();
    private List<ResponseItem> responseItemList = null;
    private List<ErrorItem> errorItemList = null;
    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/SB_FI_FA_ImportAssetRetirmentSrv", "SB_FI_FA_ImportAssetRetirmentSrv");

    public ImportAssetRetirmentSrv() {
    }

    public void setSrvInputItems(List<ImportAssetRetirmentSrvInputItem> srvInputItems) {
        this.srvInputItems = srvInputItems;
    }

    public SrvReturnMessage getReturnMessage() {
        return returnMessage;
    }

    public List<ResponseItem> getResponseItemList() {
        return responseItemList;
    }

    public List<ErrorItem> getErrorItemList() {
        return errorItemList;
    }

    public void excute() {
        URL wsdlURL = SBFIFAImportAssetRetirmentSrv_Service.WSDL_LOCATION;

        SBFIFAImportAssetRetirmentSrv_Service ss = new SBFIFAImportAssetRetirmentSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFAImportAssetRetirmentSrv port = ss.getSBFIFAImportAssetRetirmentSrvPort();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
        httpClientPolicy.setConnectionTimeout(1000000000);//连接时间
        httpClientPolicy.setReceiveTimeout(1000000000);//接收时间
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);

        {
            System.out.println("Invoking process...");
            ImportAssetRetirmentSrvRequest _process_payload = null;
            _process_payload = new ImportAssetRetirmentSrvRequest();
            MsgHeader msgHeader = new MsgHeader();
            _process_payload.setMsgHeader(msgHeader);
            ImportAssetRetirmentSrvInputCollection collection = new ImportAssetRetirmentSrvInputCollection();

            if (srvInputItems != null) {
                for (int i = 0; i < srvInputItems.size(); i++) {
                    ImportAssetRetirmentSrvInputItem inputItem = srvInputItems.get(i);
                    collection.getImportAssetRetirmentSrvInputItem().add(inputItem);
                }
            }
            //传递数据集到request中
            _process_payload.setImportAssetRetirmentSrvInputCollection(collection);   

            ImportAssetRetirmentSrvResponse _process__return = port.process(_process_payload);
            System.out.println("process.result=" + _process__return.getErrorFlag() + "||" + _process__return.getErrorMessage());
            returnMessage.setErrorFlag(StrUtil.nullToString(_process__return.getErrorFlag()));
            returnMessage.setErrorMessage(_process__return.getErrorMessage());

            if (_process__return.getErrorFlag().equals("Y")) {
                responseItemList = _process__return.getResponseCollecion().getResponseItem();
                System.out.println("结果Y: "+responseItemList);
            } else {
                errorItemList = _process__return.getErrorCollection().getErrorItem();
                int s1= errorItemList.size();
                for(int i=0;i<s1;i++){
                	System.out.println("结果N: "+errorItemList.get(0).getERRORMESSAGE());
                }
            }

        }
    }
    public String toString() {
        String s = null;
        
        return s;
    }  
    
    public static void main(String[] args) throws CalendarException, DatatypeConfigurationException {
        ImportAssetRetirmentSrv srv = new ImportAssetRetirmentSrv();
        List<ImportAssetRetirmentSrvInputItem> inputItems = new ArrayList<ImportAssetRetirmentSrvInputItem>();

        ImportAssetRetirmentSrvInputItem inputItem = null;
        inputItem = new ImportAssetRetirmentSrvInputItem();
        inputItem.setPRIKEY("111111");
        inputItem.setBOOKTYPECODE("SXMC_FA_4129");
        inputItem.setTAGNUMBER("4129-10001426");
        inputItem.setDESCRIPTION("test");
        inputItem.setDATERRETIRED(XMLGregorianCalendarUtil.getXMLGregorianCalendar("2011-07-08"));
        //inputItem.setRETIREMENTPRORATE("");
        inputItem.setRETIREMENTTYPECODE("销售");//NORMAL、TRANSFER
        inputItem.setCURRENTCOST(new BigDecimal(33814.29).setScale(2,BigDecimal.ROUND_HALF_UP));
        inputItem.setRETIREMENTCOST(new BigDecimal(11.00).setScale(2,BigDecimal.ROUND_HALF_UP));
        inputItem.setUNITSRETIRED(new BigDecimal(1));
        inputItem.setCREATEDBY(new BigDecimal(3893));
        inputItem.setEMPLOYEENUMBER(""); 
        inputItems.add(inputItem);

        srv.setSrvInputItems(inputItems);
        srv.excute();
    }

}