
/*
 * 
 */

package com.sino.soa.mis.eip.hr.hr.sb_hr_hr_inquiryempbaseinfosrv;

import com.sino.soa.common.SOAConstant;
import com.sino.soa.common.SOAVersion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 16:14:02 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_HR_HR_InquiryEmpBaseInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/hr/SB_HR_HR_InquiryEmpBaseInfoSrv/" + SOAVersion.EMP_BASE_INFO_SRV_VERSION + "/SB_HR_HR_InquiryEmpBaseInfoSrv?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/SB_HR_HR_InquiryEmpBaseInfoSrv") 
public class SBHRHRInquiryEmpBaseInfoSrv_Service extends Service {
    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://xmlns.oracle.com/SB_HR_HR_InquiryEmpBaseInfoSrv", "SB_HR_HR_InquiryEmpBaseInfoSrv");
    public final static QName SBHRHRInquiryEmpBaseInfoSrvPort = new QName("http://xmlns.oracle.com/SB_HR_HR_InquiryEmpBaseInfoSrv", "SB_HR_HR_InquiryEmpBaseInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/hr/SB_HR_HR_InquiryEmpBaseInfoSrv/" + SOAVersion.EMP_BASE_INFO_SRV_VERSION + "/SB_HR_HR_InquiryEmpBaseInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/hr/SB_HR_HR_InquiryEmpBaseInfoSrv/" + SOAVersion.EMP_BASE_INFO_SRV_VERSION + "/SB_HR_HR_InquiryEmpBaseInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBHRHRInquiryEmpBaseInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBHRHRInquiryEmpBaseInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBHRHRInquiryEmpBaseInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBHRHRInquiryEmpBaseInfoSrv
     */
    @WebEndpoint(name = "SB_HR_HR_InquiryEmpBaseInfoSrvPort")
    public SBHRHRInquiryEmpBaseInfoSrv getSBHRHRInquiryEmpBaseInfoSrvPort() {
        return super.getPort(SBHRHRInquiryEmpBaseInfoSrvPort, SBHRHRInquiryEmpBaseInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBHRHRInquiryEmpBaseInfoSrv
     */
    @WebEndpoint(name = "SB_HR_HR_InquiryEmpBaseInfoSrvPort")
    public SBHRHRInquiryEmpBaseInfoSrv getSBHRHRInquiryEmpBaseInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBHRHRInquiryEmpBaseInfoSrvPort, SBHRHRInquiryEmpBaseInfoSrv.class, features);
    }

}
