package com.sino.soa.td.eip.sc.pa.sb_sc_pa_pageinquirytaskinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Oct 14 14:52:15 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryTaskInfoSrv", name = "SB_SC_PA_PageInquiryTaskInfoSrv")
@XmlSeeAlso({ObjectFactory.class, com.sino.soa.td.eip.sc.pa.sb_sc_pa_pageinquirytaskinfosrv.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBSCPAPageInquiryTaskInfoSrv {

    @WebResult(name = "PageInquiryTaskInfoSrvResponse", targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryTaskInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public PageInquiryTaskInfoSrvResponse process(
        @WebParam(partName = "payload", name = "PageInquiryTaskInfoSrvRequest", targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryTaskInfoSrv")
        PageInquiryTaskInfoSrvRequest payload
    );
}
