
package com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetlocationsrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Sep 07 17:02:03 CST 2011
 * Generated source version: 2.1.4
 * date:2011-09-08
 * DSC:查询资产地点接口_TD(客户端)
 */

public final class SBFIFAPageInquiryAssetLocationSrv_SBFIFAPageInquiryAssetLocationSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_PageInquiryAssetLocationSrv", "SB_FI_FA_TDPageInquiryAssetLocationSrv");

    private SBFIFAPageInquiryAssetLocationSrv_SBFIFAPageInquiryAssetLocationSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIFATDPageInquiryAssetLocationSrv.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIFATDPageInquiryAssetLocationSrv ss = new SBFIFATDPageInquiryAssetLocationSrv(wsdlURL, SERVICE_NAME);
        SBFIFAPageInquiryAssetLocationSrv port = ss.getSBFIFAPageInquiryAssetLocationSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetlocationsrv.PageInquiryAssetLocationSrvRequest _process_payload = null;
        com.sino.soa.td.eip.fi.fa.sb_fi_fa_pageinquiryassetlocationsrv.PageInquiryAssetLocationSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
