
/*
 * 
 */

package com.sino.hn.todo.cxf.service.todoservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 20 17:27:28 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "TodoService", 
                  wsdlLocation = "http://10.87.9.32:9080/todoWs/services/TodoService?wsdl",
                  targetNamespace = "http://service.todo.mochasoft.com/TodoService") 
public class TodoService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.todo.mochasoft.com/TodoService", "TodoService");
    public final static QName TodoServiceHttpPort = new QName("http://service.todo.mochasoft.com/TodoService", "TodoServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.87.9.32:9080/todoWs/services/TodoService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.87.9.32:9080/todoWs/services/TodoService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TodoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TodoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TodoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TodoServicePortType
     */
    @WebEndpoint(name = "TodoServiceHttpPort")
    public TodoServicePortType getTodoServiceHttpPort() {
        return super.getPort(TodoServiceHttpPort, TodoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TodoServicePortType
     */
    @WebEndpoint(name = "TodoServiceHttpPort")
    public TodoServicePortType getTodoServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(TodoServiceHttpPort, TodoServicePortType.class, features);
    }

}
