
package com.sino.hn.todo.cxf.service.todoservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 20 17:27:28 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class TodoServicePortType_TodoServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.todo.mochasoft.com/TodoService", "TodoService");

    private TodoServicePortType_TodoServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TodoService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TodoService ss = new TodoService(wsdlURL, SERVICE_NAME);
        TodoServicePortType port = ss.getTodoServiceHttpPort();  
        
        {
        System.out.println("Invoking saveClose...");
        com.sino.hn.todo.cxf.beans.ArrayOfClose _saveClose_in0 = null;
        java.lang.String _saveClose__return = port.saveClose(_saveClose_in0);
        System.out.println("saveClose.result=" + _saveClose__return);


        }
        {
        System.out.println("Invoking saveOpen...");
        com.sino.hn.todo.cxf.beans.ArrayOfOpen _saveOpen_in0 = null;
        java.lang.String _saveOpen__return = port.saveOpen(_saveOpen_in0);
        System.out.println("saveOpen.result=" + _saveOpen__return);


        }
        {
        System.out.println("Invoking saveCancel...");
        com.sino.hn.todo.cxf.beans.ArrayOfCancel _saveCancel_in0 = null;
        java.lang.String _saveCancel__return = port.saveCancel(_saveCancel_in0);
        System.out.println("saveCancel.result=" + _saveCancel__return);


        }
        {
        System.out.println("Invoking updateTodo...");
        java.lang.String _updateTodo_in0 = "";
        java.lang.String _updateTodo_in1 = "";
        com.sino.hn.todo.cxf.service.todoservice.ArrayOfString _updateTodo_in2 = null;
        java.lang.String _updateTodo__return = port.updateTodo(_updateTodo_in0, _updateTodo_in1, _updateTodo_in2);
        System.out.println("updateTodo.result=" + _updateTodo__return);


        }
        {
        System.out.println("Invoking deleteTodo...");
        java.lang.String _deleteTodo_in0 = "";
        com.sino.hn.todo.cxf.service.todoservice.ArrayOfString _deleteTodo_in1 = null;
        java.lang.String _deleteTodo__return = port.deleteTodo(_deleteTodo_in0, _deleteTodo_in1);
        System.out.println("deleteTodo.result=" + _deleteTodo__return);


        }

        System.exit(0);
    }

}
