
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sino.hn.todo.cxf.service.todoservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 20 17:27:28 CST 2011
 * Generated source version: 2.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "TodoService",
                      portName = "TodoServiceHttpPort",
                      targetNamespace = "http://service.todo.mochasoft.com/TodoService",
                      wsdlLocation = "http://10.87.9.32:9080/todoWs/services/TodoService?wsdl",
                      endpointInterface = "com.mochasoft.todo.service.todoservice.TodoServicePortType")
                      
public class TodoServicePortTypeImpl implements TodoServicePortType {

    private static final Logger LOG = Logger.getLogger(TodoServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mochasoft.todo.service.todoservice.TodoServicePortType#saveClose(com.mochasoft.todo.beans.ArrayOfClose  in0 )*
     */
    public java.lang.String saveClose(com.sino.hn.todo.cxf.beans.ArrayOfClose in0) { 
        LOG.info("Executing operation saveClose");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mochasoft.todo.service.todoservice.TodoServicePortType#saveOpen(com.mochasoft.todo.beans.ArrayOfOpen  in0 )*
     */
    public java.lang.String saveOpen(com.sino.hn.todo.cxf.beans.ArrayOfOpen in0) { 
        LOG.info("Executing operation saveOpen");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mochasoft.todo.service.todoservice.TodoServicePortType#saveCancel(com.mochasoft.todo.cxf.beans.ArrayOfCancel  in0 )*
     */
    public java.lang.String saveCancel(com.sino.hn.todo.cxf.beans.ArrayOfCancel in0) { 
        LOG.info("Executing operation saveCancel");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mochasoft.todo.service.todoservice.TodoServicePortType#updateTodo(java.lang.String  in0 ,)java.lang.String  in1 ,)com.mochasoft.todo.service.todoservice.ArrayOfString  in2 )*
     */
    public java.lang.String updateTodo(java.lang.String in0,java.lang.String in1,com.sino.hn.todo.cxf.service.todoservice.ArrayOfString in2) { 
        LOG.info("Executing operation updateTodo");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mochasoft.todo.service.todoservice.TodoServicePortType#deleteTodo(java.lang.String  in0 ,)com.mochasoft.todo.service.todoservice.ArrayOfString  in1 )*
     */
    public java.lang.String deleteTodo(java.lang.String in0,com.sino.hn.todo.cxf.service.todoservice.ArrayOfString in1) { 
        LOG.info("Executing operation deleteTodo");
        System.out.println(in0);
        System.out.println(in1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
