
package com.sino.hn.todo.cxf.service.todoservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Oct 20 17:27:28 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
public class TodoServicePortType_TodoServiceHttpPort_Server{

    protected TodoServicePortType_TodoServiceHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new TodoServicePortTypeImpl();
        String address = "http://10.87.9.32:9080/todoWs/services/TodoService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new TodoServicePortType_TodoServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
