package com.sino.soa.td.eip.fi.fa.sb_fi_fa_bimportassetloccombsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Sep 26 14:59:06 CST 2011
 * Generated source version: 2.1.4
 * 资产地点组合批量导入_TD
 */
 
@WebService(targetNamespace = "http://eip.zte.com/SB_FI_FA_BImportAssetLocCombSrv", name = "SB_FI_FA_BImportAssetLocCombSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFABImportAssetLocCombSrv {

    @WebResult(name = "BImportAssetLocCombSrvResponse", targetNamespace = "http://eip.zte.com/SB_FI_FA_BImportAssetLocCombSrv", partName = "payload")
    @WebMethod(action = "process")
    public BImportAssetLocCombSrvResponse process(
        @WebParam(partName = "payload", name = "BImportAssetLocCombSrvRequest", targetNamespace = "http://eip.zte.com/SB_FI_FA_BImportAssetLocCombSrv")
        BImportAssetLocCombSrvRequest payload
    );
}
