
package com.sino.soa.td.eip.fi.gl.sb_fi_gl_pageinquiryaccountbalancesrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Oct 15 20:04:23 CST 2011
 * Generated source version: 2.1.4
 * 
 */

public final class SBFIGLPageInquiryAccountBalanceSrv_SBFIGLPageInquiryAccountBalanceSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://mss.cmcc.com/SB_FI_GL_PageInquiryAccountBalanceSrv", "SB_FI_GL_TDPageInquiryAccountBalanceSrv");

    private SBFIGLPageInquiryAccountBalanceSrv_SBFIGLPageInquiryAccountBalanceSrvPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SBFIGLTDPageInquiryAccountBalanceSrv.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBFIGLTDPageInquiryAccountBalanceSrv ss = new SBFIGLTDPageInquiryAccountBalanceSrv(wsdlURL, SERVICE_NAME);
        SBFIGLPageInquiryAccountBalanceSrv port = ss.getSBFIGLPageInquiryAccountBalanceSrvPort();  
        
        {
        System.out.println("Invoking process...");
        com.sino.soa.td.eip.fi.gl.sb_fi_gl_pageinquiryaccountbalancesrv.SBFIGLPageInquiryAccountBalanceSrvRequest _process_payload = null;
        com.sino.soa.td.eip.fi.gl.sb_fi_gl_pageinquiryaccountbalancesrv.SBFIGLPageInquiryAccountBalanceSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
