
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transassetdeprecationsrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Oct 12 11:15:14 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TransAssetDeprecationSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetDeprecationSrv/1.0/SB_FI_FA_TransAssetDeprecationSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDeprecationSrv") 
public class SBFIFATransAssetDeprecationSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetDeprecationSrv", "SB_FI_FA_TransAssetDeprecationSrv");
    public final static QName SBFIFATransAssetDeprecationSrvPort = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetDeprecationSrv", "SB_FI_FA_TransAssetDeprecationSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetDeprecationSrv/1.0/SB_FI_FA_TransAssetDeprecationSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/odi/SB_FI_FA_TransAssetDeprecationSrv/1.0/SB_FI_FA_TransAssetDeprecationSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATransAssetDeprecationSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATransAssetDeprecationSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATransAssetDeprecationSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFATransAssetDeprecationSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransAssetDeprecationSrvPort")
    public SBFIFATransAssetDeprecationSrv getSBFIFATransAssetDeprecationSrvPort() {
        return super.getPort(SBFIFATransAssetDeprecationSrvPort, SBFIFATransAssetDeprecationSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFATransAssetDeprecationSrv
     */
    @WebEndpoint(name = "SB_FI_FA_TransAssetDeprecationSrvPort")
    public SBFIFATransAssetDeprecationSrv getSBFIFATransAssetDeprecationSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFATransAssetDeprecationSrvPort, SBFIFATransAssetDeprecationSrv.class, features);
    }

}
