package com.sino.soa.mis.eip.sc.po.sb_sc_pa_pageinquiryprojectinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Oct 12 21:04:46 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryProjectInfoSrv", name = "SB_SC_PA_PageInquiryProjectInfoSrv")
@XmlSeeAlso({ObjectFactory.class, com.sino.soa.mis.eip.sc.po.sb_sc_pa_pageinquiryprojectinfosrv.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBSCPAPageInquiryProjectInfoSrv {

    @WebResult(name = "PageInquiryProjectInfoSrvResponse", targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryProjectInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public PageInquiryProjectInfoSrvResponse process(
        @WebParam(partName = "payload", name = "PageInquiryProjectInfoSrvRequest", targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryProjectInfoSrv")
        PageInquiryProjectInfoSrvRequest payload
    );
}
