
/*
 * 
 */

package com.sino.soa.mis.eip.sc.po.sb_sc_pa_pageinquiryprojectinfosrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Oct 12 21:04:46 CST 2011
 * Generated source version: 2.1.4
 * 查询项目信息
 */


@WebServiceClient(name = "SB_SC_PA_PageInquiryProjectInfoSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PA_PageInquiryProjectInfoSrv/3.0/SB_SC_PA_PageInquiryProjectInfoSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/SC/SB_SC_PA_PageInquiryProjectInfoSrv") 
public class SBSCPAPageInquiryProjectInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/SC/SB_SC_PA_PageInquiryProjectInfoSrv", "SB_SC_PA_PageInquiryProjectInfoSrv");
    public final static QName SBSCPAPageInquiryProjectInfoSrvPort = new QName("http://eip.zte.com/SC/SB_SC_PA_PageInquiryProjectInfoSrv", "SB_SC_PA_PageInquiryProjectInfoSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PA_PageInquiryProjectInfoSrv/3.0/SB_SC_PA_PageInquiryProjectInfoSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/sc/SB_SC_PA_PageInquiryProjectInfoSrv/3.0/SB_SC_PA_PageInquiryProjectInfoSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBSCPAPageInquiryProjectInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBSCPAPageInquiryProjectInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBSCPAPageInquiryProjectInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBSCPAPageInquiryProjectInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PA_PageInquiryProjectInfoSrvPort")
    public SBSCPAPageInquiryProjectInfoSrv getSBSCPAPageInquiryProjectInfoSrvPort() {
        return super.getPort(SBSCPAPageInquiryProjectInfoSrvPort, SBSCPAPageInquiryProjectInfoSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBSCPAPageInquiryProjectInfoSrv
     */
    @WebEndpoint(name = "SB_SC_PA_PageInquiryProjectInfoSrvPort")
    public SBSCPAPageInquiryProjectInfoSrv getSBSCPAPageInquiryProjectInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(SBSCPAPageInquiryProjectInfoSrvPort, SBSCPAPageInquiryProjectInfoSrv.class, features);
    }

}
