
/*
 * 
 */

package com.sino.soa.mis.eip.fi.fa.sb_fi_fa_bimportassetloccombsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.sino.soa.common.SOAConstant;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Sep 26 14:52:34 CST 2011
 * Generated source version: 2.1.4
 * 资产地点组合批量导入
 */


@WebServiceClient(name = "SB_FI_FA_BImportAssetLocCombSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_BImportAssetLocCombSrv/2.0/SB_FI_FA_BImportAssetLocCombSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/SB_FI_FA_BImportAssetLocCombSrv") 
public class SBFIFABImportAssetLocCombSrv_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/SB_FI_FA_BImportAssetLocCombSrv", "SB_FI_FA_BImportAssetLocCombSrv");
    public final static QName SBFIFABImportAssetLocCombSrvPort = new QName("http://eip.zte.com/SB_FI_FA_BImportAssetLocCombSrv", "SB_FI_FA_BImportAssetLocCombSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_BImportAssetLocCombSrv/2.0/SB_FI_FA_BImportAssetLocCombSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from "+"http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/fi/SB_FI_FA_BImportAssetLocCombSrv/2.0/SB_FI_FA_BImportAssetLocCombSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFABImportAssetLocCombSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFABImportAssetLocCombSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFABImportAssetLocCombSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFABImportAssetLocCombSrv
     */
    @WebEndpoint(name = "SB_FI_FA_BImportAssetLocCombSrvPort")
    public SBFIFABImportAssetLocCombSrv getSBFIFABImportAssetLocCombSrvPort() {
        return super.getPort(SBFIFABImportAssetLocCombSrvPort, SBFIFABImportAssetLocCombSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFABImportAssetLocCombSrv
     */
    @WebEndpoint(name = "SB_FI_FA_BImportAssetLocCombSrvPort")
    public SBFIFABImportAssetLocCombSrv getSBFIFABImportAssetLocCombSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFABImportAssetLocCombSrvPort, SBFIFABImportAssetLocCombSrv.class, features);
    }

}
