package com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Sep 15 17:43:08 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferIntercompanysSrv", name = "SB_FI_FA_CreateAssetTransferIntercompanysSrv")
@XmlSeeAlso({com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv.createassettransferintercompanyssrv.ObjectFactory.class, com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv.msgheader.ObjectFactory.class, com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv.importsrvresponse.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFACreateAssetTransferIntercompanysSrv {

    @WebResult(name = "CreateAssetTransferIntercompanysSrvResponse", targetNamespace = "http://eip.zte.com/common/fa/CreateAssetTransferIntercompanysSrv", partName = "payload")
    @WebMethod(action = "process")
    public com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv.importsrvresponse.ImportSrvResponse process(
        @WebParam(partName = "payload", name = "CreateAssetTransferIntercompanysSrvRequest", targetNamespace = "http://eip.zte.com/common/fa/CreateAssetTransferIntercompanysSrv")
        com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv.createassettransferintercompanyssrv.CreateAssetTransferIntercompanysSrvRequest payload
    );
}
