
/*
 * 
 */

package com.sino.soa.td.eip.fi.fa.sb_fi_fa_createassettransferintercompanyssrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Sep 15 17:43:08 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TDCreateAssetTransferIntercompanysSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDCreateAssetTransferIntercompanysSrv/1.0/SB_FI_FA_TDCreateAssetTransferIntercompanysSrv?wsdl",
                  targetNamespace = "http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferIntercompanysSrv") 
public class SBFIFATDCreateAssetTransferIntercompanysSrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferIntercompanysSrv", "SB_FI_FA_TDCreateAssetTransferIntercompanysSrv");
    public final static QName SBFIFACreateAssetTransferIntercompanysSrvPort = new QName("http://eip.zte.com/common/fa/SB_FI_FA_CreateAssetTransferIntercompanysSrv", "SB_FI_FA_CreateAssetTransferIntercompanysSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDCreateAssetTransferIntercompanysSrv/1.0/SB_FI_FA_TDCreateAssetTransferIntercompanysSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDCreateAssetTransferIntercompanysSrv/1.0/SB_FI_FA_TDCreateAssetTransferIntercompanysSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATDCreateAssetTransferIntercompanysSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATDCreateAssetTransferIntercompanysSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATDCreateAssetTransferIntercompanysSrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFACreateAssetTransferIntercompanysSrv
     */
    @WebEndpoint(name = "SB_FI_FA_CreateAssetTransferIntercompanysSrvPort")
    public SBFIFACreateAssetTransferIntercompanysSrv getSBFIFACreateAssetTransferIntercompanysSrvPort() {
        return super.getPort(SBFIFACreateAssetTransferIntercompanysSrvPort, SBFIFACreateAssetTransferIntercompanysSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFACreateAssetTransferIntercompanysSrv
     */
    @WebEndpoint(name = "SB_FI_FA_CreateAssetTransferIntercompanysSrvPort")
    public SBFIFACreateAssetTransferIntercompanysSrv getSBFIFACreateAssetTransferIntercompanysSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFACreateAssetTransferIntercompanysSrvPort, SBFIFACreateAssetTransferIntercompanysSrv.class, features);
    }

}
