package com.sino.soa.mis.srv.assetcustdetail.srv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.SBFIFATransMetaCustDetailSrv_Service;  //SBFIFATransAssetCustDetailSrv_Service;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.SBFIFATransMetaCustDetailSrv;    //SBFIFATransAssetCustDetailSrv;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.SBFIFATransMetaCustDetailSrvProcessRequest;   //SBFIFATransAssetCustDetailSrvProcessRequest;
import com.sino.soa.mis.eip.fi.fa.sb_fi_fa_transmetacustdetailsrv.SBFIFATransMetaCustDetailSrvProcessResponse;
import com.sino.soa.common.SrvReturnMessage;
import com.sino.soa.util.XMLGregorianCalendarUtil;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.datatype.DatatypeConfigurationException;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import com.sino.base.util.StrUtil;
import com.sino.base.exception.CalendarException;

/**
 * This class was generated by Apache CXF 2.1.4
 * Sat Aug 22 14:32:53 CST 2009
 * Generated source version: 2.1.4
 * 查询转资物料清单_非TD(ODI) 
 */

public final class TransAssetCustDetailSrv {
    private SrvReturnMessage srvMessage = new SrvReturnMessage();

    private String envCode = "";
    private String bookTypeCode = "";
    private String projectNumber = "";
    private String taskNum = "";
    private String capitalizedDateFrom = "";
    private String capitalizedDateTo = "";

   // private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransAssetCustDetailSrv", "SB_FI_FA_TransAssetCustDetailSrv");
    private static final QName SERVICE_NAME = new QName("http://eip.zte.com/fi/SB_FI_FA_TransMetaCustDetailSrv", "SB_FI_FA_TransMetaCustDetailSrv");

    public TransAssetCustDetailSrv() {
    }

    public void excute() throws CalendarException, DatatypeConfigurationException {
        URL wsdlURL = SBFIFATransMetaCustDetailSrv_Service.WSDL_LOCATION;

        SBFIFATransMetaCustDetailSrv_Service ss = new SBFIFATransMetaCustDetailSrv_Service(wsdlURL, SERVICE_NAME);
        SBFIFATransMetaCustDetailSrv port = ss.getSBFIFATransMetaCustDetailSrvPort();//      getSBFIFATransAssetCustDetailSrvPort();

        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();

        httpClientPolicy.setConnectionTimeout(5400000);//连接时间
        httpClientPolicy.setReceiveTimeout(5400000);//接收时间
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);

        {
            System.out.println("TransAssetCustDetailSrv Invoking process...");
            SBFIFATransMetaCustDetailSrvProcessRequest _process_payload = null;
            _process_payload = new SBFIFATransMetaCustDetailSrvProcessRequest();
            _process_payload.setENVCODE(getEnvCode());
            //_process_payload.setBOOKTYPECODE(getBookTypeCode());
            _process_payload.setPROJECTNUMBER(getProjectNumber());
            _process_payload.setTASKNUM(getTaskNum());
            _process_payload.setCAPITALIZEDDATEFROM(XMLGregorianCalendarUtil.getXMLGregorianCalendar(getCapitalizedDateFrom()));
            _process_payload.setCAPITALIZEDDATETO(XMLGregorianCalendarUtil.getXMLGregorianCalendar(getCapitalizedDateTo()));
            long start = System.currentTimeMillis();
            SBFIFATransMetaCustDetailSrvProcessResponse _process__return = port.process(_process_payload);
            srvMessage.setErrorFlag(StrUtil.nullToString(_process__return.getERRORFLAG()));
            srvMessage.setErrorMessage(_process__return.getERRORMESSAGE());
            System.out.println("process.result=" + _process__return.getINSTANCEID() + "||" + _process__return.getERRORFLAG() + "||" + _process__return.getERRORMESSAGE());
            System.out.println("耗时" + (System.currentTimeMillis() - start) + "毫秒");
        }
    }

    public SrvReturnMessage getSrvMessage() {
        return srvMessage;
    }

    public String getEnvCode() {
        return envCode;
    }

    public void setEnvCode(String envCode) {
        this.envCode = envCode;
    }

    public String getBookTypeCode() {
        return bookTypeCode;
    }

    public void setBookTypeCode(String bookTypeCode) {
        this.bookTypeCode = bookTypeCode;
    }

    public String getProjectNumber() {
        return projectNumber;
    }

    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber;
    }

    public String getTaskNum() {
        return taskNum;
    }

    public void setTaskNum(String taskNum) {
        this.taskNum = taskNum;
    }

    public String getCapitalizedDateFrom() {
        return capitalizedDateFrom;
    }

    public void setCapitalizedDateFrom(String capitalizedDateFrom) {
        this.capitalizedDateFrom = capitalizedDateFrom;
    }

    public String getCapitalizedDateTo() {
        return capitalizedDateTo;
    }

    public void setCapitalizedDateTo(String capitalizedDateTo) {
        this.capitalizedDateTo = capitalizedDateTo;
    }

    public static void main(String[] args) {

    }
}