package com.sino.soa.td.eip.fi.fa.sb_fi_fa_inquiryassettagnumbersrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Oct 18 19:08:01 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://mss.cmcc.com/SB_FI_FA_InquiryAssetTagNumberSrv", name = "SB_FI_FA_InquiryAssetTagNumberSrv")
@XmlSeeAlso({ObjectFactory.class, com.sino.soa.td.eip.fi.fa.sb_fi_fa_inquiryassettagnumbersrv.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFAInquiryAssetTagNumberSrv {

    @WebResult(name = "SB_FI_FA_InquiryAssetTagNumberSrvResponse", targetNamespace = "http://mss.cmcc.com/SB_FI_FA_InquiryAssetTagNumberSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIFAInquiryAssetTagNumberSrvResponse process(
        @WebParam(partName = "payload", name = "SB_FI_FA_InquiryAssetTagNumberSrvRequest", targetNamespace = "http://mss.cmcc.com/SB_FI_FA_InquiryAssetTagNumberSrv")
        SBFIFAInquiryAssetTagNumberSrvRequest payload
    );
}
