
/*
 * 
 */

package com.sino.soa.td.eip.fi.fa.sb_fi_fa_inquiryassettagnumbersrv;

import com.sino.soa.common.SOAConstant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Oct 18 19:08:01 CST 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SB_FI_FA_TDInquiryAssetTagNumberSrv", 
                  wsdlLocation = "http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDInquiryAssetTagNumberSrv/1.0/SB_FI_FA_TDInquiryAssetTagNumberSrv?wsdl",
                  targetNamespace = "http://mss.cmcc.com/SB_FI_FA_InquiryAssetTagNumberSrv") 
public class SBFIFATDInquiryAssetTagNumberSrv extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://mss.cmcc.com/SB_FI_FA_InquiryAssetTagNumberSrv", "SB_FI_FA_TDInquiryAssetTagNumberSrv");
    public final static QName SBFIFAInquiryAssetTagNumberSrvPort = new QName("http://mss.cmcc.com/SB_FI_FA_InquiryAssetTagNumberSrv", "SB_FI_FA_InquiryAssetTagNumberSrvPort");
    static {
        URL url = null;
        try {
            url = new URL("http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDInquiryAssetTagNumberSrv/1.0/SB_FI_FA_TDInquiryAssetTagNumberSrv?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://"+ SOAConstant.SERVER_NAME+":"+ SOAConstant.SERVER_PORT+"/orabpel/td/SB_FI_FA_TDInquiryAssetTagNumberSrv/1.0/SB_FI_FA_TDInquiryAssetTagNumberSrv?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SBFIFATDInquiryAssetTagNumberSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBFIFATDInquiryAssetTagNumberSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBFIFATDInquiryAssetTagNumberSrv() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SBFIFAInquiryAssetTagNumberSrv
     */
    @WebEndpoint(name = "SB_FI_FA_InquiryAssetTagNumberSrvPort")
    public SBFIFAInquiryAssetTagNumberSrv getSBFIFAInquiryAssetTagNumberSrvPort() {
        return super.getPort(SBFIFAInquiryAssetTagNumberSrvPort, SBFIFAInquiryAssetTagNumberSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBFIFAInquiryAssetTagNumberSrv
     */
    @WebEndpoint(name = "SB_FI_FA_InquiryAssetTagNumberSrvPort")
    public SBFIFAInquiryAssetTagNumberSrv getSBFIFAInquiryAssetTagNumberSrvPort(WebServiceFeature... features) {
        return super.getPort(SBFIFAInquiryAssetTagNumberSrvPort, SBFIFAInquiryAssetTagNumberSrv.class, features);
    }

}
