package com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetdistributionsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Oct 10 20:45:57 CST 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDistributionSrv", name = "SB_FI_FA_TransAssetDistributionSrv")
@XmlSeeAlso({ObjectFactory.class, com.sino.soa.td.eip.fi.fa.sb_fi_fa_transassetdistributionsrv.odi_variables.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBFIFATransAssetDistributionSrv {

    @WebResult(name = "SB_FI_FA_TransAssetDistributionSrvProcessResponse", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDistributionSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBFIFATransAssetDistributionSrvProcessResponse process(
        @WebParam(partName = "payload", name = "SB_FI_FA_TransAssetDistributionSrvProcessRequest", targetNamespace = "http://eip.zte.com/fi/SB_FI_FA_TransAssetDistributionSrv")
        SBFIFATransAssetDistributionSrvProcessRequest payload
    );
}
